// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alteracoes_cad_paciente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alteracoes_cad_paciente));
        
        string IMigrationMetadata.Id
        {
            get { return "201710272005595_Alteracoes_cad_paciente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
