// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reformulate_laboratorio_do_suprimento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reformulate_laboratorio_do_suprimento));
        
        string IMigrationMetadata.Id
        {
            get { return "201712061924435_reformulate_laboratorio_do_suprimento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
