// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GeorgeExclusao_EstoqueTipoMovimento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GeorgeExclusao_EstoqueTipoMovimento));
        
        string IMigrationMetadata.Id
        {
            get { return "201708281709492_GeorgeExclusao_EstoqueTipoMovimento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
