// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GeorgeInclusaoUnidade_ImportacaoProduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GeorgeInclusaoUnidade_ImportacaoProduto));
        
        string IMigrationMetadata.Id
        {
            get { return "201712141329154_GeorgeInclusaoUnidade_ImportacaoProduto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
