namespace SW10.SWMANAGER.Migrations
{
    using System.Data.Entity.Migrations;

    public partial class Inclusao_campo_codigo_CamposPadraoCRUD : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.TipoAtendimento", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Convenio", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Cep", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Cidade", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Estado", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Pais", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Empresa", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Est_Estoque", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Plano", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Medico", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Nacionalidade", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Naturalidade", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Profissao", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Guia", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.GrupoTipoTabelaDominio", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.TipoAcomodacao", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.MotivoAltaTipoAlta", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Origem", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Paciente", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.PacientePeso", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ParecerEspecialista", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ParecerEspecialistaResposta", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.FormResposta", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.FormData", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ColConfig", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ColMultiOption", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.FormConfig", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.RowConfig", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Prestador", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Conselho", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.TipoParticipacao", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.TipoPrestador", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.TipoVinculoEmpregaticio", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.UserEmpresas", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.AgendamentoConsultaMedicoDisponibilidade", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Intervalo", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.AgendamentoConsulta", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Atestado", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.TipoAtestado", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.CentroCusto", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.GrupoCentroCusto", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Cfop", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ClassificacaoRisco", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.PreAtendimento", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ConsultorOcorrencia", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ConsultorTipoDadoNF", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ControleProducao", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.CorPele", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Entrada", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.EntradaItem", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Est_GrupoClasse", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Est_Grupo", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Est_GrupoSubClasse", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Est_Genero", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Est_ProdutoUnidade", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Est_UnidadeTipo", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Est_Unidade", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Est_ProdutoEstoque", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Escolaridade", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.EstadoCivil", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.EstoqueMovimentoItem", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.EstoqueMovimento", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.EstoquePreMovimento", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.EstTipoMovimento", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.EstTipoOperacao", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Fornecedor", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.FornecedorPessoaFisica", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.FornecedorPessoaJuridica", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.MotivoPerdaProduto", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.OrdemCompra", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.EstoquePreMovimentoEstado", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.TipoFrete", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.EstoqueMovimentoLoteValidade", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.LoteValidade", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoLaboratorio", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.EstoquePreMovimentoItem", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.EstoquePreMovimentoLoteValidade", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.EstoqueTransferenciaProduto", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.EstoqueTransferenciaProdutoItem", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.EvolucaoMedica", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.FatBrasImport", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.FatBrasIndice", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.FatBrasPreco", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.FatGrupo", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.FatTipoGrupo", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.FatTabelaPrecoItem", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Favorito", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Feriado", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.GrauInstrucao", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.GrupoProcedimento", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.GuiaCampo", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.GuiaTipo", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Indicacao", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.InstituicaoTransferencia", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.MailingTemplate", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ModeloAtestado", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.MotivoCancelamento", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.MotivoCaucao", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.MotivoTransferenciaLeito", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.NotaFiscal", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Orcamento", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.PacienteConvenioBloqueado", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Parentesco", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.PrestadorCredenciamento", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.PrestadorGrupoProcedimento", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoAcaoTerapeutica", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Est_ProdutoEmpresa", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoGrupoTratamento", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoLocalizacao", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoPalavraChave", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoRelacaoAcaoTerapeutica", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoRelacaoLaboratorio", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoRelacaoPalavraChave", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoRelacaoPortaria", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoRelacaoUnidade", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoTipoUnidade", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoSaldoEmprestimo", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoSaldo", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoClasse", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoGrupo", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoSubClasse", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoListaSubstituicao", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.ProdutoSubstancia", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.RelacaoGuiaCampo", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Religiao", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.Sexo", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.SisMoedaCotacaoItem", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.SisMoedaCotacao", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.SisMoedaCotacaoPlano", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.AssSolicitacaoExameItem", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.TenantLogo", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.TipoEntrada", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.TipoLeito", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.TipoTelefone", "Codigo", c => c.String(maxLength: 10));
            AddColumn("dbo.TipoUnidade", "Codigo", c => c.String(maxLength: 10));
            AlterColumn("dbo.AdmissaoMedica", "Codigo", c => c.String(maxLength: 10));
            AlterColumn("dbo.Atendimento", "Codigo", c => c.String(maxLength: 10));
            AlterColumn("dbo.Especialidade", "Codigo", c => c.String(maxLength: 10));
            AlterColumn("dbo.Leito", "Codigo", c => c.String(maxLength: 10));
            AlterColumn("dbo.VersaoTiss", "Codigo", c => c.String(maxLength: 10));
            AlterColumn("dbo.TipoSanguineo", "Codigo", c => c.String(maxLength: 10));
            AlterColumn("dbo.ServicoMedicoPrestado", "Codigo", c => c.String(maxLength: 10));
            AlterColumn("dbo.AssistencialAtendimento", "Codigo", c => c.String(maxLength: 10));
            AlterColumn("dbo.CapituloCID", "Codigo", c => c.String(maxLength: 10));
            AlterColumn("dbo.Est_DCB", "Codigo", c => c.String(maxLength: 10));
            AlterColumn("dbo.Est_EstoqueLocalizacao", "Codigo", c => c.String(maxLength: 10));
            AlterColumn("dbo.FatItemTabela", "Codigo", c => c.String(maxLength: 10));
            AlterColumn("dbo.SisMoeda", "Codigo", c => c.String(maxLength: 10));
            AlterColumn("dbo.AssPrescricaoMedica", "Codigo", c => c.String(maxLength: 10));
            AlterColumn("dbo.UltimoId", "Codigo", c => c.String(maxLength: 10));
        }

        public override void Down()
        {
            AlterColumn("dbo.UltimoId", "Codigo", c => c.String());
            AlterColumn("dbo.AssPrescricaoMedica", "Codigo", c => c.String());
            AlterColumn("dbo.SisMoeda", "Codigo", c => c.String());
            AlterColumn("dbo.FatItemTabela", "Codigo", c => c.String());
            AlterColumn("dbo.Est_EstoqueLocalizacao", "Codigo", c => c.String());
            AlterColumn("dbo.Est_DCB", "Codigo", c => c.String());
            AlterColumn("dbo.CapituloCID", "Codigo", c => c.String());
            AlterColumn("dbo.AssistencialAtendimento", "Codigo", c => c.String());
            AlterColumn("dbo.ServicoMedicoPrestado", "Codigo", c => c.String());
            AlterColumn("dbo.TipoSanguineo", "Codigo", c => c.String());
            AlterColumn("dbo.VersaoTiss", "Codigo", c => c.String());
            AlterColumn("dbo.Leito", "Codigo", c => c.String());
            AlterColumn("dbo.Especialidade", "Codigo", c => c.String());
            AlterColumn("dbo.Atendimento", "Codigo", c => c.String());
            AlterColumn("dbo.AdmissaoMedica", "Codigo", c => c.String());
            DropColumn("dbo.TipoUnidade", "Codigo");
            DropColumn("dbo.TipoTelefone", "Codigo");
            DropColumn("dbo.TipoLeito", "Codigo");
            DropColumn("dbo.TipoEntrada", "Codigo");
            DropColumn("dbo.TenantLogo", "Codigo");
            DropColumn("dbo.AssSolicitacaoExameItem", "Codigo");
            DropColumn("dbo.SisMoedaCotacaoPlano", "Codigo");
            DropColumn("dbo.SisMoedaCotacao", "Codigo");
            DropColumn("dbo.SisMoedaCotacaoItem", "Codigo");
            DropColumn("dbo.Sexo", "Codigo");
            DropColumn("dbo.Religiao", "Codigo");
            DropColumn("dbo.RelacaoGuiaCampo", "Codigo");
            DropColumn("dbo.ProdutoSubstancia", "Codigo");
            DropColumn("dbo.ProdutoListaSubstituicao", "Codigo");
            DropColumn("dbo.ProdutoSubClasse", "Codigo");
            DropColumn("dbo.ProdutoGrupo", "Codigo");
            DropColumn("dbo.ProdutoClasse", "Codigo");
            DropColumn("dbo.ProdutoSaldo", "Codigo");
            DropColumn("dbo.ProdutoSaldoEmprestimo", "Codigo");
            DropColumn("dbo.ProdutoTipoUnidade", "Codigo");
            DropColumn("dbo.ProdutoRelacaoUnidade", "Codigo");
            DropColumn("dbo.ProdutoRelacaoPortaria", "Codigo");
            DropColumn("dbo.ProdutoRelacaoPalavraChave", "Codigo");
            DropColumn("dbo.ProdutoRelacaoLaboratorio", "Codigo");
            DropColumn("dbo.ProdutoRelacaoAcaoTerapeutica", "Codigo");
            DropColumn("dbo.ProdutoPalavraChave", "Codigo");
            DropColumn("dbo.ProdutoLocalizacao", "Codigo");
            DropColumn("dbo.ProdutoGrupoTratamento", "Codigo");
            DropColumn("dbo.Est_ProdutoEmpresa", "Codigo");
            DropColumn("dbo.ProdutoAcaoTerapeutica", "Codigo");
            DropColumn("dbo.PrestadorGrupoProcedimento", "Codigo");
            DropColumn("dbo.PrestadorCredenciamento", "Codigo");
            DropColumn("dbo.Parentesco", "Codigo");
            DropColumn("dbo.PacienteConvenioBloqueado", "Codigo");
            DropColumn("dbo.Orcamento", "Codigo");
            DropColumn("dbo.NotaFiscal", "Codigo");
            DropColumn("dbo.MotivoTransferenciaLeito", "Codigo");
            DropColumn("dbo.MotivoCaucao", "Codigo");
            DropColumn("dbo.MotivoCancelamento", "Codigo");
            DropColumn("dbo.ModeloAtestado", "Codigo");
            DropColumn("dbo.MailingTemplate", "Codigo");
            DropColumn("dbo.InstituicaoTransferencia", "Codigo");
            DropColumn("dbo.Indicacao", "Codigo");
            DropColumn("dbo.GuiaTipo", "Codigo");
            DropColumn("dbo.GuiaCampo", "Codigo");
            DropColumn("dbo.GrupoProcedimento", "Codigo");
            DropColumn("dbo.GrauInstrucao", "Codigo");
            DropColumn("dbo.Feriado", "Codigo");
            DropColumn("dbo.Favorito", "Codigo");
            DropColumn("dbo.FatTabelaPrecoItem", "Codigo");
            DropColumn("dbo.FatTipoGrupo", "Codigo");
            DropColumn("dbo.FatGrupo", "Codigo");
            DropColumn("dbo.FatBrasPreco", "Codigo");
            DropColumn("dbo.FatBrasIndice", "Codigo");
            DropColumn("dbo.FatBrasImport", "Codigo");
            DropColumn("dbo.EvolucaoMedica", "Codigo");
            DropColumn("dbo.EstoqueTransferenciaProdutoItem", "Codigo");
            DropColumn("dbo.EstoqueTransferenciaProduto", "Codigo");
            DropColumn("dbo.EstoquePreMovimentoLoteValidade", "Codigo");
            DropColumn("dbo.EstoquePreMovimentoItem", "Codigo");
            DropColumn("dbo.ProdutoLaboratorio", "Codigo");
            DropColumn("dbo.LoteValidade", "Codigo");
            DropColumn("dbo.EstoqueMovimentoLoteValidade", "Codigo");
            DropColumn("dbo.TipoFrete", "Codigo");
            DropColumn("dbo.EstoquePreMovimentoEstado", "Codigo");
            DropColumn("dbo.OrdemCompra", "Codigo");
            DropColumn("dbo.MotivoPerdaProduto", "Codigo");
            DropColumn("dbo.FornecedorPessoaJuridica", "Codigo");
            DropColumn("dbo.FornecedorPessoaFisica", "Codigo");
            DropColumn("dbo.Fornecedor", "Codigo");
            DropColumn("dbo.EstTipoOperacao", "Codigo");
            DropColumn("dbo.EstTipoMovimento", "Codigo");
            DropColumn("dbo.EstoquePreMovimento", "Codigo");
            DropColumn("dbo.EstoqueMovimento", "Codigo");
            DropColumn("dbo.EstoqueMovimentoItem", "Codigo");
            DropColumn("dbo.EstadoCivil", "Codigo");
            DropColumn("dbo.Escolaridade", "Codigo");
            DropColumn("dbo.Est_ProdutoEstoque", "Codigo");
            DropColumn("dbo.Est_Unidade", "Codigo");
            DropColumn("dbo.Est_UnidadeTipo", "Codigo");
            DropColumn("dbo.Est_ProdutoUnidade", "Codigo");
            DropColumn("dbo.Est_Genero", "Codigo");
            DropColumn("dbo.Est_GrupoSubClasse", "Codigo");
            DropColumn("dbo.Est_Grupo", "Codigo");
            DropColumn("dbo.Est_GrupoClasse", "Codigo");
            DropColumn("dbo.EntradaItem", "Codigo");
            DropColumn("dbo.Entrada", "Codigo");
            DropColumn("dbo.CorPele", "Codigo");
            DropColumn("dbo.ControleProducao", "Codigo");
            DropColumn("dbo.ConsultorTipoDadoNF", "Codigo");
            DropColumn("dbo.ConsultorOcorrencia", "Codigo");
            DropColumn("dbo.PreAtendimento", "Codigo");
            DropColumn("dbo.ClassificacaoRisco", "Codigo");
            DropColumn("dbo.Cfop", "Codigo");
            DropColumn("dbo.GrupoCentroCusto", "Codigo");
            DropColumn("dbo.CentroCusto", "Codigo");
            DropColumn("dbo.TipoAtestado", "Codigo");
            DropColumn("dbo.Atestado", "Codigo");
            DropColumn("dbo.AgendamentoConsulta", "Codigo");
            DropColumn("dbo.Intervalo", "Codigo");
            DropColumn("dbo.AgendamentoConsultaMedicoDisponibilidade", "Codigo");
            DropColumn("dbo.UserEmpresas", "Codigo");
            DropColumn("dbo.TipoVinculoEmpregaticio", "Codigo");
            DropColumn("dbo.TipoPrestador", "Codigo");
            DropColumn("dbo.TipoParticipacao", "Codigo");
            DropColumn("dbo.Conselho", "Codigo");
            DropColumn("dbo.Prestador", "Codigo");
            DropColumn("dbo.RowConfig", "Codigo");
            DropColumn("dbo.FormConfig", "Codigo");
            DropColumn("dbo.ColMultiOption", "Codigo");
            DropColumn("dbo.ColConfig", "Codigo");
            DropColumn("dbo.FormData", "Codigo");
            DropColumn("dbo.FormResposta", "Codigo");
            DropColumn("dbo.ParecerEspecialistaResposta", "Codigo");
            DropColumn("dbo.ParecerEspecialista", "Codigo");
            DropColumn("dbo.PacientePeso", "Codigo");
            DropColumn("dbo.Paciente", "Codigo");
            DropColumn("dbo.Origem", "Codigo");
            DropColumn("dbo.MotivoAltaTipoAlta", "Codigo");
            DropColumn("dbo.TipoAcomodacao", "Codigo");
            DropColumn("dbo.GrupoTipoTabelaDominio", "Codigo");
            DropColumn("dbo.Guia", "Codigo");
            DropColumn("dbo.Profissao", "Codigo");
            DropColumn("dbo.Naturalidade", "Codigo");
            DropColumn("dbo.Nacionalidade", "Codigo");
            DropColumn("dbo.Medico", "Codigo");
            DropColumn("dbo.Plano", "Codigo");
            DropColumn("dbo.Est_Estoque", "Codigo");
            DropColumn("dbo.Empresa", "Codigo");
            DropColumn("dbo.Pais", "Codigo");
            DropColumn("dbo.Estado", "Codigo");
            DropColumn("dbo.Cidade", "Codigo");
            DropColumn("dbo.Cep", "Codigo");
            DropColumn("dbo.Convenio", "Codigo");
            DropColumn("dbo.TipoAtendimento", "Codigo");
        }
    }
}
