// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class inclusao_produtoempresa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inclusao_produtoempresa));
        
        string IMigrationMetadata.Id
        {
            get { return "201707252142002_inclusao_produtoempresa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
