// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Pablo_Atendimento_20170630 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pablo_Atendimento_20170630));
        
        string IMigrationMetadata.Id
        {
            get { return "201706302147288_Pablo_Atendimento_20170630"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
