// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fat_Remocao_GrupoProcedimento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fat_Remocao_GrupoProcedimento));
        
        string IMigrationMetadata.Id
        {
            get { return "201708232011257_Fat_Remocao_GrupoProcedimento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
