namespace SW10.SWMANAGER.Migrations
{
    using System.Data.Entity.Migrations;

    public partial class Incluindo_Descricao_CamposPadraoCRUD : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.AssAdmissaoMedica", "Descricao", c => c.String());
            AddColumn("dbo.Atendimento", "Descricao", c => c.String());
            AddColumn("dbo.SisConvenio", "Descricao", c => c.String());
            AddColumn("dbo.SisCep", "Descricao", c => c.String());
            AddColumn("dbo.SisEstado", "Descricao", c => c.String());
            AddColumn("dbo.SisPessoa", "Descricao", c => c.String());
            AddColumn("dbo.SisEmpresa", "Descricao", c => c.String());
            AddColumn("dbo.SisEspecialidade", "Descricao", c => c.String());
            AddColumn("dbo.SisMedico", "Descricao", c => c.String());
            AddColumn("dbo.SisVersaoTiss", "Descricao", c => c.String());
            AddColumn("dbo.SisPaciente", "Descricao", c => c.String());
            AddColumn("dbo.PacientePeso", "Descricao", c => c.String());
            AddColumn("dbo.AssParecerEspecialista", "Descricao", c => c.String());
            AddColumn("dbo.AssParecerEspecialistaResposta", "Descricao", c => c.String());
            AddColumn("dbo.SisFormResposta", "Descricao", c => c.String());
            AddColumn("dbo.SisFormData", "Descricao", c => c.String());
            AddColumn("dbo.SisFormColConfig", "Descricao", c => c.String());
            AddColumn("dbo.SisFormColMultiOption", "Descricao", c => c.String());
            AddColumn("dbo.SisFormConfig", "Descricao", c => c.String());
            AddColumn("dbo.SisFormRowConfig", "Descricao", c => c.String());
            AddColumn("dbo.UserEmpresas", "Descricao", c => c.String());
            AddColumn("dbo.AgendamentoConsultaMedicoDisponibilidade", "Descricao", c => c.String());
            AddColumn("dbo.Intervalo", "Descricao", c => c.String());
            AddColumn("dbo.AgendamentoConsulta", "Descricao", c => c.String());
            AddColumn("dbo.AssistencialAtendimento", "Descricao", c => c.String());
            AddColumn("dbo.AssAtestado", "Descricao", c => c.String());
            AddColumn("dbo.AssModeloAtestado", "Descricao", c => c.String());
            AddColumn("dbo.AteVisitante", "Descricao", c => c.String());
            AddColumn("dbo.FornecedorPessoaFisica", "Descricao", c => c.String());
            AddColumn("dbo.FornecedorPessoaJuridica", "Descricao", c => c.String());
            AddColumn("dbo.ClassificacaoRisco", "Descricao", c => c.String());
            AddColumn("dbo.LabTecnico", "Descricao", c => c.String());
            AddColumn("dbo.AssDivisaoTipoResposta", "Descricao", c => c.String());
            AddColumn("dbo.AssTipoRespostaAssTipoRespostaConfig", "Descricao", c => c.String());
            AddColumn("dbo.AssTipoRespostaConfigElementoHtml", "Descricao", c => c.String());
            AddColumn("dbo.Entrada", "Descricao", c => c.String());
            AddColumn("dbo.EntradaItem", "Descricao", c => c.String());
            AddColumn("dbo.Est_ProdutoUnidade", "Descricao", c => c.String());
            AddColumn("dbo.Est_ProdutoEstoque", "Descricao", c => c.String());
            AddColumn("dbo.EstMovimentoBaixa", "Descricao", c => c.String());
            AddColumn("dbo.EstoqueMovimento", "Descricao", c => c.String());
            AddColumn("dbo.EstoquePreMovimento", "Descricao", c => c.String());
            AddColumn("dbo.EstMovimentoBaixaItem", "Descricao", c => c.String());
            AddColumn("dbo.EstoqueMovimentoItem", "Descricao", c => c.String());
            AddColumn("dbo.EstoquePreMovimentoItem", "Descricao", c => c.String());
            AddColumn("dbo.EstBaixaEmprestimoItem", "Descricao", c => c.String());
            AddColumn("dbo.EstBaixaEmprestimo", "Descricao", c => c.String());
            AddColumn("dbo.EstoqueMovimentoLoteValidade", "Descricao", c => c.String());
            AddColumn("dbo.LoteValidade", "Descricao", c => c.String());
            AddColumn("dbo.EstoquePreMovimentoLoteValidade", "Descricao", c => c.String());
            AddColumn("dbo.Est_EstoqueEmpresa", "Descricao", c => c.String());
            AddColumn("dbo.Est_EstoqueGrupo", "Descricao", c => c.String());
            AddColumn("dbo.EstoqueTransferenciaProduto", "Descricao", c => c.String());
            AddColumn("dbo.EstoqueTransferenciaProdutoItem", "Descricao", c => c.String());
            AddColumn("dbo.AssEvolucaoMedica", "Descricao", c => c.String());
            AddColumn("dbo.FatBrasImport", "Descricao", c => c.String());
            AddColumn("dbo.FatBrasIndice", "Descricao", c => c.String());
            AddColumn("dbo.FatBrasPreco", "Descricao", c => c.String());
            AddColumn("dbo.FatConfigConvenio", "Descricao", c => c.String());
            AddColumn("dbo.FatConta", "Descricao", c => c.String());
            AddColumn("dbo.FatTabelaPrecoItem", "Descricao", c => c.String());
            AddColumn("dbo.SisFavorito", "Descricao", c => c.String());
            AddColumn("dbo.SisFormConfigOperacao", "Descricao", c => c.String());
            AddColumn("dbo.SisFormConfigUnidadeOrganizacional", "Descricao", c => c.String());
            AddColumn("dbo.AssFormTipoResposta", "Descricao", c => c.String());
            AddColumn("dbo.LabKitExameItem", "Descricao", c => c.String());
            AddColumn("dbo.LauMovimento", "Descricao", c => c.String());
            AddColumn("dbo.LauMovimentoItem", "Descricao", c => c.String());
            AddColumn("dbo.AssSolicitacaoExameItem", "Descricao", c => c.String());
            AddColumn("dbo.AssSolicitacaoExame", "Descricao", c => c.String());
            AddColumn("dbo.AssPrescricaoMedica", "Descricao", c => c.String());
            AddColumn("dbo.MailingTemplate", "Descricao", c => c.String());
            AddColumn("dbo.NotaFiscal", "Descricao", c => c.String());
            AddColumn("dbo.PacienteConvenioBloqueado", "Descricao", c => c.String());
            AddColumn("dbo.PrestadorCredenciamento", "Descricao", c => c.String());
            AddColumn("dbo.PrestadorGrupoProcedimento", "Descricao", c => c.String());
            AddColumn("dbo.Est_ProdutoEmpresa", "Descricao", c => c.String());
            AddColumn("dbo.ProdutoPalavraChave", "Descricao", c => c.String());
            AddColumn("dbo.ProdutoRelacaoAcaoTerapeutica", "Descricao", c => c.String());
            AddColumn("dbo.ProdutoRelacaoLaboratorio", "Descricao", c => c.String());
            AddColumn("dbo.ProdutoRelacaoPalavraChave", "Descricao", c => c.String());
            AddColumn("dbo.ProdutoRelacaoPortaria", "Descricao", c => c.String());
            AddColumn("dbo.ProdutoRelacaoUnidade", "Descricao", c => c.String());
            AddColumn("dbo.ProdutoSaldoEmprestimo", "Descricao", c => c.String());
            AddColumn("dbo.ProdutoSaldo", "Descricao", c => c.String());
            AddColumn("dbo.ProdutoListaSubstituicao", "Descricao", c => c.String());
            AddColumn("dbo.RelacaoGuiaCampo", "Descricao", c => c.String());
            AddColumn("dbo.SisMoedaCotacaoItem", "Descricao", c => c.String());
            AddColumn("dbo.SisMoedaCotacao", "Descricao", c => c.String());
            AddColumn("dbo.SisMoedaCotacaoPlano", "Descricao", c => c.String());
            AddColumn("dbo.TenantLogo", "Descricao", c => c.String());
            AddColumn("dbo.TipoUnidade", "Descricao", c => c.String());
            AddColumn("dbo.SisUltimoId", "Descricao", c => c.String());
        }

        public override void Down()
        {
            DropColumn("dbo.SisUltimoId", "Descricao");
            DropColumn("dbo.TipoUnidade", "Descricao");
            DropColumn("dbo.TenantLogo", "Descricao");
            DropColumn("dbo.SisMoedaCotacaoPlano", "Descricao");
            DropColumn("dbo.SisMoedaCotacao", "Descricao");
            DropColumn("dbo.SisMoedaCotacaoItem", "Descricao");
            DropColumn("dbo.RelacaoGuiaCampo", "Descricao");
            DropColumn("dbo.ProdutoListaSubstituicao", "Descricao");
            DropColumn("dbo.ProdutoSaldo", "Descricao");
            DropColumn("dbo.ProdutoSaldoEmprestimo", "Descricao");
            DropColumn("dbo.ProdutoRelacaoUnidade", "Descricao");
            DropColumn("dbo.ProdutoRelacaoPortaria", "Descricao");
            DropColumn("dbo.ProdutoRelacaoPalavraChave", "Descricao");
            DropColumn("dbo.ProdutoRelacaoLaboratorio", "Descricao");
            DropColumn("dbo.ProdutoRelacaoAcaoTerapeutica", "Descricao");
            DropColumn("dbo.ProdutoPalavraChave", "Descricao");
            DropColumn("dbo.Est_ProdutoEmpresa", "Descricao");
            DropColumn("dbo.PrestadorGrupoProcedimento", "Descricao");
            DropColumn("dbo.PrestadorCredenciamento", "Descricao");
            DropColumn("dbo.PacienteConvenioBloqueado", "Descricao");
            DropColumn("dbo.NotaFiscal", "Descricao");
            DropColumn("dbo.MailingTemplate", "Descricao");
            DropColumn("dbo.AssPrescricaoMedica", "Descricao");
            DropColumn("dbo.AssSolicitacaoExame", "Descricao");
            DropColumn("dbo.AssSolicitacaoExameItem", "Descricao");
            DropColumn("dbo.LauMovimentoItem", "Descricao");
            DropColumn("dbo.LauMovimento", "Descricao");
            DropColumn("dbo.LabKitExameItem", "Descricao");
            DropColumn("dbo.AssFormTipoResposta", "Descricao");
            DropColumn("dbo.SisFormConfigUnidadeOrganizacional", "Descricao");
            DropColumn("dbo.SisFormConfigOperacao", "Descricao");
            DropColumn("dbo.SisFavorito", "Descricao");
            DropColumn("dbo.FatTabelaPrecoItem", "Descricao");
            DropColumn("dbo.FatConta", "Descricao");
            DropColumn("dbo.FatConfigConvenio", "Descricao");
            DropColumn("dbo.FatBrasPreco", "Descricao");
            DropColumn("dbo.FatBrasIndice", "Descricao");
            DropColumn("dbo.FatBrasImport", "Descricao");
            DropColumn("dbo.AssEvolucaoMedica", "Descricao");
            DropColumn("dbo.EstoqueTransferenciaProdutoItem", "Descricao");
            DropColumn("dbo.EstoqueTransferenciaProduto", "Descricao");
            DropColumn("dbo.Est_EstoqueGrupo", "Descricao");
            DropColumn("dbo.Est_EstoqueEmpresa", "Descricao");
            DropColumn("dbo.EstoquePreMovimentoLoteValidade", "Descricao");
            DropColumn("dbo.LoteValidade", "Descricao");
            DropColumn("dbo.EstoqueMovimentoLoteValidade", "Descricao");
            DropColumn("dbo.EstBaixaEmprestimo", "Descricao");
            DropColumn("dbo.EstBaixaEmprestimoItem", "Descricao");
            DropColumn("dbo.EstoquePreMovimentoItem", "Descricao");
            DropColumn("dbo.EstoqueMovimentoItem", "Descricao");
            DropColumn("dbo.EstMovimentoBaixaItem", "Descricao");
            DropColumn("dbo.EstoquePreMovimento", "Descricao");
            DropColumn("dbo.EstoqueMovimento", "Descricao");
            DropColumn("dbo.EstMovimentoBaixa", "Descricao");
            DropColumn("dbo.Est_ProdutoEstoque", "Descricao");
            DropColumn("dbo.Est_ProdutoUnidade", "Descricao");
            DropColumn("dbo.EntradaItem", "Descricao");
            DropColumn("dbo.Entrada", "Descricao");
            DropColumn("dbo.AssTipoRespostaConfigElementoHtml", "Descricao");
            DropColumn("dbo.AssTipoRespostaAssTipoRespostaConfig", "Descricao");
            DropColumn("dbo.AssDivisaoTipoResposta", "Descricao");
            DropColumn("dbo.LabTecnico", "Descricao");
            DropColumn("dbo.ClassificacaoRisco", "Descricao");
            DropColumn("dbo.FornecedorPessoaJuridica", "Descricao");
            DropColumn("dbo.FornecedorPessoaFisica", "Descricao");
            DropColumn("dbo.AteVisitante", "Descricao");
            DropColumn("dbo.AssModeloAtestado", "Descricao");
            DropColumn("dbo.AssAtestado", "Descricao");
            DropColumn("dbo.AssistencialAtendimento", "Descricao");
            DropColumn("dbo.AgendamentoConsulta", "Descricao");
            DropColumn("dbo.Intervalo", "Descricao");
            DropColumn("dbo.AgendamentoConsultaMedicoDisponibilidade", "Descricao");
            DropColumn("dbo.UserEmpresas", "Descricao");
            DropColumn("dbo.SisFormRowConfig", "Descricao");
            DropColumn("dbo.SisFormConfig", "Descricao");
            DropColumn("dbo.SisFormColMultiOption", "Descricao");
            DropColumn("dbo.SisFormColConfig", "Descricao");
            DropColumn("dbo.SisFormData", "Descricao");
            DropColumn("dbo.SisFormResposta", "Descricao");
            DropColumn("dbo.AssParecerEspecialistaResposta", "Descricao");
            DropColumn("dbo.AssParecerEspecialista", "Descricao");
            DropColumn("dbo.PacientePeso", "Descricao");
            DropColumn("dbo.SisPaciente", "Descricao");
            DropColumn("dbo.SisVersaoTiss", "Descricao");
            DropColumn("dbo.SisMedico", "Descricao");
            DropColumn("dbo.SisEspecialidade", "Descricao");
            DropColumn("dbo.SisEmpresa", "Descricao");
            DropColumn("dbo.SisPessoa", "Descricao");
            DropColumn("dbo.SisEstado", "Descricao");
            DropColumn("dbo.SisCep", "Descricao");
            DropColumn("dbo.SisConvenio", "Descricao");
            DropColumn("dbo.Atendimento", "Descricao");
            DropColumn("dbo.AssAdmissaoMedica", "Descricao");
        }
    }
}
