// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FatConta_Advinhando_Campos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FatConta_Advinhando_Campos));
        
        string IMigrationMetadata.Id
        {
            get { return "201709121828092_FatConta_Advinhando_Campos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
