// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Marcus_Diferencas_entre_branches_20170713 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Marcus_Diferencas_entre_branches_20170713));
        
        string IMigrationMetadata.Id
        {
            get { return "201707132136356_Marcus_Diferencas_entre_branches_20170713"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
