// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Marcus_Substituicao_UnidadeInternacao_por_UnidadeOrganizacional_Modulos_Assistenciais : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Marcus_Substituicao_UnidadeInternacao_por_UnidadeOrganizacional_Modulos_Assistenciais));
        
        string IMigrationMetadata.Id
        {
            get { return "201706281920468_Marcus_Substituicao_UnidadeInternacao_por_UnidadeOrganizacional_Modulos_Assistenciais"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
