// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Marcus_Adicionando_Referencia_Classe_Id_FormResposta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Marcus_Adicionando_Referencia_Classe_Id_FormResposta));
        
        string IMigrationMetadata.Id
        {
            get { return "201707101753281_Marcus_Adicionando_Referencia_Classe_Id_FormResposta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
