// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Projeto_Conteudo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Projeto_Conteudo));
        
        string IMigrationMetadata.Id
        {
            get { return "201712141714011_Projeto_Conteudo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
