// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class exclusao_do_campo_codigo_da_classe_produto_para_uso_do_campo_que_vem_da_heranca_campospadraocrud : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(exclusao_do_campo_codigo_da_classe_produto_para_uso_do_campo_que_vem_da_heranca_campospadraocrud));
        
        string IMigrationMetadata.Id
        {
            get { return "201710111348305_exclusao_do_campo_codigo_da_classe_produto_para_uso_do_campo_que_vem_da_heranca_campospadraocrud"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
