// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Campos_faltando_pos_merge_master_atendimento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Campos_faltando_pos_merge_master_atendimento));
        
        string IMigrationMetadata.Id
        {
            get { return "201706282204566_Campos_faltando_pos_merge_master_atendimento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
