// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Incluindo_Descricao_CamposPadraoCRUD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Incluindo_Descricao_CamposPadraoCRUD));
        
        string IMigrationMetadata.Id
        {
            get { return "201711031710435_Incluindo_Descricao_CamposPadraoCRUD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
