// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Marcus_Campos_Suprimentos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Marcus_Campos_Suprimentos));
        
        string IMigrationMetadata.Id
        {
            get { return "201707042159565_Marcus_Campos_Suprimentos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
