// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FatContaItem_Grupo_Correcoes_IsLaudo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FatContaItem_Grupo_Correcoes_IsLaudo));
        
        string IMigrationMetadata.Id
        {
            get { return "201711221906422_FatContaItem_Grupo_Correcoes_IsLaudo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
