// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class inclusao_campos_isconsigandoispadronizadoemproduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inclusao_campos_isconsigandoispadronizadoemproduto));
        
        string IMigrationMetadata.Id
        {
            get { return "201711221928377_inclusao_campos_isconsigando-ispadronizado-em-produto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
