// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rodrigo_Criacao_Classe_UltimoId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rodrigo_Criacao_Classe_UltimoId));
        
        string IMigrationMetadata.Id
        {
            get { return "201706301944307_Rodrigo_Criacao_Classe_UltimoId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
