// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Divisao_Adicionando_Relacionamento_TipoResposta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Divisao_Adicionando_Relacionamento_TipoResposta));
        
        string IMigrationMetadata.Id
        {
            get { return "201709201958126_Divisao_Adicionando_Relacionamento_TipoResposta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
