// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cad_produto_add_etiquetaid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cad_produto_add_etiquetaid));
        
        string IMigrationMetadata.Id
        {
            get { return "201707040126543_cad_produto_add_etiquetaid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
