// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alterando_stringlength_Conselho : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alterando_stringlength_Conselho));
        
        string IMigrationMetadata.Id
        {
            get { return "201809141904181_Alterando_stringlength_Conselho"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
