// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tabeleas_AgendamentosSalaCirurgicas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tabeleas_AgendamentosSalaCirurgicas));
        
        string IMigrationMetadata.Id
        {
            get { return "201812281158211_Tabeleas_AgendamentosSalaCirurgicas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
