// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tabelas_Evento_EventoMov_EventoGrupo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tabelas_Evento_EventoMov_EventoGrupo));
        
        string IMigrationMetadata.Id
        {
            get { return "201804041608528_Tabelas_Evento_EventoMov_EventoGrupo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
