// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FatItem_Referencias : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FatItem_Referencias));
        
        string IMigrationMetadata.Id
        {
            get { return "201801251559156_FatItem_Referencias"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
