// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ajustando_campos_nullable_Pro_ReqExameMov_e_MovItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ajustando_campos_nullable_Pro_ReqExameMov_e_MovItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201810251849301_Ajustando_campos_nullable_Pro_ReqExameMov_e_MovItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
