// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlteracaoDocumento_Pessoa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlteracaoDocumento_Pessoa));
        
        string IMigrationMetadata.Id
        {
            get { return "201802012003266_AlteracaoDocumento_Pessoa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
