// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Adicionando_HoraInicialPrescricao_em_UnidadeOrganizacional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adicionando_HoraInicialPrescricao_em_UnidadeOrganizacional));
        
        string IMigrationMetadata.Id
        {
            get { return "201805021720052_Adicionando_HoraInicialPrescricao_em_UnidadeOrganizacional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
