// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_foreing_key_requisicao_com_tiporequisicao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_foreing_key_requisicao_com_tiporequisicao));
        
        string IMigrationMetadata.Id
        {
            get { return "201803201932210_add_foreing_key_requisicao_com_tiporequisicao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
