// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Paciente_DataNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Paciente_DataNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201804021555422_Paciente_DataNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
