// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modifica_tipo_coluna_quantidade_requisicao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifica_tipo_coluna_quantidade_requisicao));
        
        string IMigrationMetadata.Id
        {
            get { return "201803271921582_modifica_tipo_coluna_quantidade_requisicao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
