// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Inclusao_Tabela_SisBI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inclusao_Tabela_SisBI));
        
        string IMigrationMetadata.Id
        {
            get { return "201801101803590_Inclusao_Tabela_SisBI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
