// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Diversas_Alteracoes_Assistencial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Diversas_Alteracoes_Assistencial));
        
        string IMigrationMetadata.Id
        {
            get { return "201802071710004_Diversas_Alteracoes_Assistencial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
