// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_campos_em_requsisicao_compra : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_campos_em_requsisicao_compra));
        
        string IMigrationMetadata.Id
        {
            get { return "201804120743328_add_campos_em_requsisicao_compra"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
