// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adicionando_importaid_campospadraocrud : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adicionando_importaid_campospadraocrud));
        
        string IMigrationMetadata.Id
        {
            get { return "201806152012269_adicionando_importaid_campospadraocrud"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
