// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Inserindo_relacionameto_com_FatItem_e_AssPrescricaoItem_e_FinContaAdministrativa_em_Produto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inserindo_relacionameto_com_FatItem_e_AssPrescricaoItem_e_FinContaAdministrativa_em_Produto));
        
        string IMigrationMetadata.Id
        {
            get { return "201804251833329_Inserindo_relacionameto_com_FatItem_e_AssPrescricaoItem_e_FinContaAdministrativa_em_Produto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
