// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Retirando_Codigo_Descricao_TipoAcomodacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Retirando_Codigo_Descricao_TipoAcomodacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201803261333154_Retirando_Codigo_Descricao_TipoAcomodacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
