// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Inserindo_ChavesPrimarias_VWRptAtendimentoDetalhado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inserindo_ChavesPrimarias_VWRptAtendimentoDetalhado));
        
        string IMigrationMetadata.Id
        {
            get { return "201812111124073_Inserindo_ChavesPrimarias_VWRptAtendimentoDetalhado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
