// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fat_Guia_E_Grupo_OutrasDespesas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fat_Guia_E_Grupo_OutrasDespesas));
        
        string IMigrationMetadata.Id
        {
            get { return "201802161319461_Fat_Guia_E_Grupo_OutrasDespesas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
