// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alterando_campo_isAtivo_em_produto_para_bool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterando_campo_isAtivo_em_produto_para_bool));
        
        string IMigrationMetadata.Id
        {
            get { return "201804261402254_alterando_campo_isAtivo_em_produto_para_bool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
