namespace SW10.SWMANAGER.Migrations
{
    using System.Data.Entity.Migrations;

    public partial class adicionando_importaid_campospadraocrud : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.FinAgencia", "ImportaId", c => c.Int());
            AddColumn("dbo.FinBanco", "ImportaId", c => c.Int());
            AddColumn("dbo.AteAgendamentoConsultaMedicoDisponibilidade", "ImportaId", c => c.Int());
            AddColumn("dbo.AteIntervalo", "ImportaId", c => c.Int());
            AddColumn("dbo.SisMedico", "ImportaId", c => c.Int());
            AddColumn("dbo.SisCidade", "ImportaId", c => c.Int());
            AddColumn("dbo.SisEstado", "ImportaId", c => c.Int());
            AddColumn("dbo.SisPais", "ImportaId", c => c.Int());
            AddColumn("dbo.SisConselho", "ImportaId", c => c.Int());
            AddColumn("dbo.CorPele", "ImportaId", c => c.Int());
            AddColumn("dbo.SisEscolaridade", "ImportaId", c => c.Int());
            AddColumn("dbo.SisEstadoCivil", "ImportaId", c => c.Int());
            AddColumn("dbo.SisMedicoEspecialidade", "ImportaId", c => c.Int());
            AddColumn("dbo.SisEspecialidade", "ImportaId", c => c.Int());
            AddColumn("dbo.SisCbo", "ImportaId", c => c.Int());
            AddColumn("dbo.SisCboFamilia", "ImportaId", c => c.Int());
            AddColumn("dbo.SisCboTipo", "ImportaId", c => c.Int());
            AddColumn("dbo.SisNacionalidade", "ImportaId", c => c.Int());
            AddColumn("dbo.SisNaturalidade", "ImportaId", c => c.Int());
            AddColumn("dbo.SisProfissao", "ImportaId", c => c.Int());
            AddColumn("dbo.SisReligiao", "ImportaId", c => c.Int());
            AddColumn("dbo.SisSexo", "ImportaId", c => c.Int());
            AddColumn("dbo.SisPessoa", "ImportaId", c => c.Int());
            AddColumn("dbo.SisEndereco", "ImportaId", c => c.Int());
            AddColumn("dbo.TipoEnderecoes", "ImportaId", c => c.Int());
            AddColumn("dbo.SisTipoLogradouro", "ImportaId", c => c.Int());
            AddColumn("dbo.SisTipoPessoa", "ImportaId", c => c.Int());
            AddColumn("dbo.SisTipoSanguineo", "ImportaId", c => c.Int());
            AddColumn("dbo.SisTipoTelefone", "ImportaId", c => c.Int());
            AddColumn("dbo.SisTipoParticipacao", "ImportaId", c => c.Int());
            AddColumn("dbo.TipoVinculoEmpregaticio", "ImportaId", c => c.Int());
            AddColumn("dbo.AgendamentoConsulta", "ImportaId", c => c.Int());
            AddColumn("dbo.SisConvenio", "ImportaId", c => c.Int());
            AddColumn("dbo.SisCep", "ImportaId", c => c.Int());
            AddColumn("dbo.SisPaciente", "ImportaId", c => c.Int());
            AddColumn("dbo.PacientePeso", "ImportaId", c => c.Int());
            AddColumn("dbo.SisPlano", "ImportaId", c => c.Int());
            AddColumn("dbo.AteAtendimentoLeitoMov", "ImportaId", c => c.Int());
            AddColumn("dbo.AteAtendimento", "ImportaId", c => c.Int());
            AddColumn("dbo.GrupoCID", "ImportaId", c => c.Int());
            AddColumn("dbo.AteTipoAtendimento", "ImportaId", c => c.Int());
            AddColumn("dbo.SisEmpresa", "ImportaId", c => c.Int());
            AddColumn("dbo.Est_Estoque", "ImportaId", c => c.Int());
            AddColumn("dbo.SisUnidadeOrganizacional", "ImportaId", c => c.Int());
            AddColumn("dbo.CentroCusto", "ImportaId", c => c.Int());
            AddColumn("dbo.GrupoCentroCusto", "ImportaId", c => c.Int());
            AddColumn("dbo.AteUnidadeInternacaoTipo", "ImportaId", c => c.Int());
            AddColumn("dbo.FatGuia", "ImportaId", c => c.Int());
            AddColumn("dbo.SisGuia", "ImportaId", c => c.Int());
            AddColumn("dbo.AteLeito", "ImportaId", c => c.Int());
            AddColumn("dbo.LeitoStatus", "ImportaId", c => c.Int());
            AddColumn("dbo.SisTabelaDominio", "ImportaId", c => c.Int());
            AddColumn("dbo.SisGrupoTipoTabelaDominio", "ImportaId", c => c.Int());
            AddColumn("dbo.SisTipoTabelaDominio", "ImportaId", c => c.Int());
            AddColumn("dbo.SisVersaoTiss", "ImportaId", c => c.Int());
            AddColumn("dbo.SisTipoAcomodacao", "ImportaId", c => c.Int());
            AddColumn("dbo.AssMotivoAlta", "ImportaId", c => c.Int());
            AddColumn("dbo.AssMotivoAltaTipoAlta", "ImportaId", c => c.Int());
            AddColumn("dbo.SisOrigem", "ImportaId", c => c.Int());
            AddColumn("dbo.ServicoMedicoPrestado", "ImportaId", c => c.Int());
            AddColumn("dbo.UserEmpresas", "ImportaId", c => c.Int());
            AddColumn("dbo.AssAtestado", "ImportaId", c => c.Int());
            AddColumn("dbo.AssModeloAtestado", "ImportaId", c => c.Int());
            AddColumn("dbo.AssTipoAtestado", "ImportaId", c => c.Int());
            AddColumn("dbo.AteVisitante", "ImportaId", c => c.Int());
            AddColumn("dbo.SisFornecedor", "ImportaId", c => c.Int());
            AddColumn("dbo.AteAutorizacaoProcedimento", "ImportaId", c => c.Int());
            AddColumn("dbo.AteAutorizacaoProcedimentoItem", "ImportaId", c => c.Int());
            AddColumn("dbo.FatItem", "ImportaId", c => c.Int());
            AddColumn("dbo.FatBrasItem", "ImportaId", c => c.Int());
            AddColumn("dbo.LabEquipamento", "ImportaId", c => c.Int());
            AddColumn("dbo.LabExame", "ImportaId", c => c.Int());
            AddColumn("dbo.LabFormata", "ImportaId", c => c.Int());
            AddColumn("dbo.LabMapa", "ImportaId", c => c.Int());
            AddColumn("dbo.LabMaterial", "ImportaId", c => c.Int());
            AddColumn("dbo.LabMetodo", "ImportaId", c => c.Int());
            AddColumn("dbo.LabSetor", "ImportaId", c => c.Int());
            AddColumn("dbo.LabUnidade", "ImportaId", c => c.Int());
            AddColumn("dbo.FatGrupo", "ImportaId", c => c.Int());
            AddColumn("dbo.FatTipoGrupo", "ImportaId", c => c.Int());
            AddColumn("dbo.FatKit", "ImportaId", c => c.Int());
            AddColumn("dbo.LauGrupo", "ImportaId", c => c.Int());
            AddColumn("dbo.LauModalidade", "ImportaId", c => c.Int());
            AddColumn("dbo.FatSubGrupo", "ImportaId", c => c.Int());
            AddColumn("dbo.AteStatusSolicitacaoProcedimento", "ImportaId", c => c.Int());
            AddColumn("dbo.SisBairro", "ImportaId", c => c.Int());
            AddColumn("dbo.SisBI", "ImportaId", c => c.Int());
            AddColumn("dbo.SisModulo", "ImportaId", c => c.Int());
            AddColumn("dbo.SisOperacao", "ImportaId", c => c.Int());
            AddColumn("dbo.CapituloCID", "ImportaId", c => c.Int());
            AddColumn("dbo.Cfop", "ImportaId", c => c.Int());
            AddColumn("dbo.FinCheque", "ImportaId", c => c.Int());
            AddColumn("dbo.FinTalaoCheque", "ImportaId", c => c.Int());
            AddColumn("dbo.FinContaCorrente", "ImportaId", c => c.Int());
            AddColumn("dbo.FinTipoContaCorrente", "ImportaId", c => c.Int());
            AddColumn("dbo.ClassificacaoRisco", "ImportaId", c => c.Int());
            AddColumn("dbo.PreAtendimento", "ImportaId", c => c.Int());
            AddColumn("dbo.SisFormColConfig", "ImportaId", c => c.Int());
            AddColumn("dbo.SisFormColMultiOption", "ImportaId", c => c.Int());
            AddColumn("dbo.SisFormData", "ImportaId", c => c.Int());
            AddColumn("dbo.SisFormResposta", "ImportaId", c => c.Int());
            AddColumn("dbo.SisFormConfig", "ImportaId", c => c.Int());
            AddColumn("dbo.SisFormRowConfig", "ImportaId", c => c.Int());
            AddColumn("dbo.SisComentario", "ImportaId", c => c.Int());
            AddColumn("dbo.SisTarefa", "ImportaId", c => c.Int());
            AddColumn("dbo.DocRotulo", "ImportaId", c => c.Int());
            AddColumn("dbo.SisProjeto", "ImportaId", c => c.Int());
            AddColumn("dbo.AteComentarioAutorizacaoProcedimento", "ImportaId", c => c.Int());
            AddColumn("dbo.CmpAprovacaoStatus", "ImportaId", c => c.Int());
            AddColumn("dbo.CmpCotacaoItem", "ImportaId", c => c.Int());
            AddColumn("dbo.Fornecedor", "ImportaId", c => c.Int());
            AddColumn("dbo.FornecedorPessoaFisica", "ImportaId", c => c.Int());
            AddColumn("dbo.FornecedorPessoaJuridica", "ImportaId", c => c.Int());
            AddColumn("dbo.SisTipoCadastroExistente", "ImportaId", c => c.Int());
            AddColumn("dbo.TipoPessoa", "ImportaId", c => c.Int());
            AddColumn("dbo.CmpRequisicaoItem", "ImportaId", c => c.Int());
            AddColumn("dbo.Est_Produto", "ImportaId", c => c.Int());
            AddColumn("dbo.Est_GrupoClasse", "ImportaId", c => c.Int());
            AddColumn("dbo.Est_Grupo", "ImportaId", c => c.Int());
            AddColumn("dbo.Est_GrupoSubClasse", "ImportaId", c => c.Int());
            AddColumn("dbo.FinContaAdministrativa", "ImportaId", c => c.Int());
            AddColumn("dbo.FinContaAdministrativaCentroCusto", "ImportaId", c => c.Int());
            AddColumn("dbo.FinContaAdministrativaEmpresa", "ImportaId", c => c.Int());
            AddColumn("dbo.FinRateioCentroCusto", "ImportaId", c => c.Int());
            AddColumn("dbo.FinRateioCentroCustoItem", "ImportaId", c => c.Int());
            AddColumn("dbo.FinSubGrupoContaAdministrativa", "ImportaId", c => c.Int());
            AddColumn("dbo.FinGrupoContaAdministrativa", "ImportaId", c => c.Int());
            AddColumn("dbo.FinGrupoDRE", "ImportaId", c => c.Int());
            AddColumn("dbo.Est_DCB", "ImportaId", c => c.Int());
            AddColumn("dbo.Est_EstoqueLocalizacao", "ImportaId", c => c.Int());
            AddColumn("dbo.Est_Genero", "ImportaId", c => c.Int());
            AddColumn("dbo.Est_ProdutoUnidade", "ImportaId", c => c.Int());
            AddColumn("dbo.Est_UnidadeTipo", "ImportaId", c => c.Int());
            AddColumn("dbo.Est_Unidade", "ImportaId", c => c.Int());
            AddColumn("dbo.CmpRequisicao", "ImportaId", c => c.Int());
            AddColumn("dbo.CmpCotacaoStatus", "ImportaId", c => c.Int());
            AddColumn("dbo.CmpMotivoPedido", "ImportaId", c => c.Int());
            AddColumn("dbo.CmpRequisicaoModo", "ImportaId", c => c.Int());
            AddColumn("dbo.CmpRequisicaoTipo", "ImportaId", c => c.Int());
            AddColumn("dbo.ConsultorOcorrencia", "ImportaId", c => c.Int());
            AddColumn("dbo.ConsultorTabela", "ImportaId", c => c.Int());
            AddColumn("dbo.ConsultorTabelaCampo", "ImportaId", c => c.Int());
            AddColumn("dbo.ConsultorTipoDadoNF", "ImportaId", c => c.Int());
            AddColumn("dbo.ControleProducao", "ImportaId", c => c.Int());
            AddColumn("dbo.AssDivisaoTipoResposta", "ImportaId", c => c.Int());
            AddColumn("dbo.AssDivisao", "ImportaId", c => c.Int());
            AddColumn("dbo.AssTipoPrescricao", "ImportaId", c => c.Int());
            AddColumn("dbo.AssTipoResposta", "ImportaId", c => c.Int());
            AddColumn("dbo.AssTipoRespostaAssTipoRespostaConfig", "ImportaId", c => c.Int());
            AddColumn("dbo.AssTipoRespostaConfig", "ImportaId", c => c.Int());
            AddColumn("dbo.AssTipoRespostaConfigElementoHtml", "ImportaId", c => c.Int());
            AddColumn("dbo.SisElementoHtml", "ImportaId", c => c.Int());
            AddColumn("dbo.SisElementoHtmlTipo", "ImportaId", c => c.Int());
            AddColumn("dbo.DocItem", "ImportaId", c => c.Int());
            AddColumn("dbo.FinDocumento", "ImportaId", c => c.Int());
            AddColumn("dbo.FinLancamento", "ImportaId", c => c.Int());
            AddColumn("dbo.FinLancamentoQuitacao", "ImportaId", c => c.Int());
            AddColumn("dbo.FinQuitacao", "ImportaId", c => c.Int());
            AddColumn("dbo.FinMeioPagamento", "ImportaId", c => c.Int());
            AddColumn("dbo.FinTipoMeioPagamento", "ImportaId", c => c.Int());
            AddColumn("dbo.FinSituacaoLancamento", "ImportaId", c => c.Int());
            AddColumn("dbo.FinDocumentoRateio", "ImportaId", c => c.Int());
            AddColumn("dbo.FinTipoDocumento", "ImportaId", c => c.Int());
            AddColumn("dbo.Entrada", "ImportaId", c => c.Int());
            AddColumn("dbo.EntradaItem", "ImportaId", c => c.Int());
            AddColumn("dbo.Est_ProdutoEstoque", "ImportaId", c => c.Int());
            AddColumn("dbo.EstMovimentoBaixa", "ImportaId", c => c.Int());
            AddColumn("dbo.EstoqueMovimento", "ImportaId", c => c.Int());
            AddColumn("dbo.EstGrupoOperacao", "ImportaId", c => c.Int());
            AddColumn("dbo.EstoquePreMovimento", "ImportaId", c => c.Int());
            AddColumn("dbo.EstTipoMovimento", "ImportaId", c => c.Int());
            AddColumn("dbo.EstTipoOperacao", "ImportaId", c => c.Int());
            AddColumn("dbo.MotivoPerdaProduto", "ImportaId", c => c.Int());
            AddColumn("dbo.OrdemCompra", "ImportaId", c => c.Int());
            AddColumn("dbo.EstoquePreMovimentoEstado", "ImportaId", c => c.Int());
            AddColumn("dbo.TipoFrete", "ImportaId", c => c.Int());
            AddColumn("dbo.EstMovimentoBaixaItem", "ImportaId", c => c.Int());
            AddColumn("dbo.EstoqueMovimentoItem", "ImportaId", c => c.Int());
            AddColumn("dbo.EstoquePreMovimentoItem", "ImportaId", c => c.Int());
            AddColumn("dbo.EstBaixaEmprestimoItem", "ImportaId", c => c.Int());
            AddColumn("dbo.EstBaixaEmprestimo", "ImportaId", c => c.Int());
            AddColumn("dbo.EstImportacaoProduto", "ImportaId", c => c.Int());
            AddColumn("dbo.EstItemSolicitacaoAtendida", "ImportaId", c => c.Int());
            AddColumn("dbo.EstSolicitacaoItem", "ImportaId", c => c.Int());
            AddColumn("dbo.EstLaboratorio", "ImportaId", c => c.Int());
            AddColumn("dbo.FatBrasLaboratorio", "ImportaId", c => c.Int());
            AddColumn("dbo.EstoqueMovimentoLoteValidade", "ImportaId", c => c.Int());
            AddColumn("dbo.LoteValidade", "ImportaId", c => c.Int());
            AddColumn("dbo.EstoquePreMovimentoLoteValidade", "ImportaId", c => c.Int());
            AddColumn("dbo.Est_EstoqueEmpresa", "ImportaId", c => c.Int());
            AddColumn("dbo.Est_EstoqueGrupo", "ImportaId", c => c.Int());
            AddColumn("dbo.EstoqueTransferenciaProduto", "ImportaId", c => c.Int());
            AddColumn("dbo.EstoqueTransferenciaProdutoItem", "ImportaId", c => c.Int());
            AddColumn("dbo.QuaEvento", "ImportaId", c => c.Int());
            AddColumn("dbo.QuaEventoGrupo", "ImportaId", c => c.Int());
            AddColumn("dbo.QuaEventoMov", "ImportaId", c => c.Int());
            AddColumn("dbo.FatAutorizacaoDetalhe", "ImportaId", c => c.Int());
            AddColumn("dbo.FatAutorizacao", "ImportaId", c => c.Int());
            AddColumn("dbo.FatBrasApresentacao", "ImportaId", c => c.Int());
            AddColumn("dbo.FatBrasImport", "ImportaId", c => c.Int());
            AddColumn("dbo.FatBrasIndice", "ImportaId", c => c.Int());
            AddColumn("dbo.FatBrasPreco", "ImportaId", c => c.Int());
            AddColumn("dbo.FatConfigConvenioGlobal", "ImportaId", c => c.Int());
            AddColumn("dbo.FatGlobal", "ImportaId", c => c.Int());
            AddColumn("dbo.FatConfigConvenio", "ImportaId", c => c.Int());
            AddColumn("dbo.FatTabela", "ImportaId", c => c.Int());
            AddColumn("dbo.FatConta", "ImportaId", c => c.Int());
            AddColumn("dbo.FatContaStatus", "ImportaId", c => c.Int());
            AddColumn("dbo.TipoLeito", "ImportaId", c => c.Int());
            AddColumn("dbo.FatContaItem", "ImportaId", c => c.Int());
            AddColumn("dbo.FatContaKit", "ImportaId", c => c.Int());
            AddColumn("dbo.Terceirizado", "ImportaId", c => c.Int());
            AddColumn("dbo.SisTurno", "ImportaId", c => c.Int());
            AddColumn("dbo.FatTabelaPrecoItem", "ImportaId", c => c.Int());
            AddColumn("dbo.SisMoeda", "ImportaId", c => c.Int());
            AddColumn("dbo.FatConvenioRelacionamento", "ImportaId", c => c.Int());
            AddColumn("dbo.FatTabelaRelacionamento", "ImportaId", c => c.Int());
            AddColumn("dbo.FatEntregaConta", "ImportaId", c => c.Int());
            AddColumn("dbo.FatEntregaLote", "ImportaId", c => c.Int());
            AddColumn("dbo.FatGrupoConvenio", "ImportaId", c => c.Int());
            AddColumn("dbo.FatGuiaConvenio", "ImportaId", c => c.Int());
            AddColumn("dbo.FatItemConfigGlobal", "ImportaId", c => c.Int());
            AddColumn("dbo.FatItemRelacionamento", "ImportaId", c => c.Int());
            AddColumn("dbo.FatFaturamentoItemAutorizacao", "ImportaId", c => c.Int());
            AddColumn("dbo.FatItemConfig", "ImportaId", c => c.Int());
            AddColumn("dbo.FatItemTabela", "ImportaId", c => c.Int());
            AddColumn("dbo.FatKitItem", "ImportaId", c => c.Int());
            AddColumn("dbo.FatTaxaEmpresa", "ImportaId", c => c.Int());
            AddColumn("dbo.FatTaxa", "ImportaId", c => c.Int());
            AddColumn("dbo.FatTaxaGrupo", "ImportaId", c => c.Int());
            AddColumn("dbo.FatTaxaLocal", "ImportaId", c => c.Int());
            AddColumn("dbo.FatTaxaTipoLeito", "ImportaId", c => c.Int());
            AddColumn("dbo.FatTaxaTurno", "ImportaId", c => c.Int());
            AddColumn("dbo.SisFavorito", "ImportaId", c => c.Int());
            AddColumn("dbo.Feriado", "ImportaId", c => c.Int());
            AddColumn("dbo.AteFila", "ImportaId", c => c.Int());
            AddColumn("dbo.AteTipoLocalChamada", "ImportaId", c => c.Int());
            AddColumn("dbo.AssFormaAplicacao", "ImportaId", c => c.Int());
            AddColumn("dbo.FinFormaPagamento", "ImportaId", c => c.Int());
            AddColumn("dbo.LabFormataItem", "ImportaId", c => c.Int());
            AddColumn("dbo.LabItemResultado", "ImportaId", c => c.Int());
            AddColumn("dbo.LabTabela", "ImportaId", c => c.Int());
            AddColumn("dbo.LabTipoResultado", "ImportaId", c => c.Int());
            AddColumn("dbo.SisFormConfigEspecialidade", "ImportaId", c => c.Int());
            AddColumn("dbo.SisFormConfigOperacao", "ImportaId", c => c.Int());
            AddColumn("dbo.SisFormConfigUnidadeOrganizacional", "ImportaId", c => c.Int());
            AddColumn("dbo.AssFormulaEstoque", "ImportaId", c => c.Int());
            AddColumn("dbo.AssPrescricaoItem", "ImportaId", c => c.Int());
            AddColumn("dbo.AssFrequencia", "ImportaId", c => c.Int());
            AddColumn("dbo.AssTipoControle", "ImportaId", c => c.Int());
            AddColumn("dbo.AssVelocidadeInfusao", "ImportaId", c => c.Int());
            AddColumn("dbo.AssFormulaFaturamento", "ImportaId", c => c.Int());
            AddColumn("dbo.GrauInstrucao", "ImportaId", c => c.Int());
            AddColumn("dbo.GrupoProcedimento", "ImportaId", c => c.Int());
            AddColumn("dbo.GuiaCampo", "ImportaId", c => c.Int());
            AddColumn("dbo.SisGuiaTipo", "ImportaId", c => c.Int());
            AddColumn("dbo.SisHoraDia", "ImportaId", c => c.Int());
            AddColumn("dbo.Indicacao", "ImportaId", c => c.Int());
            AddColumn("dbo.InstituicaoTransferencia", "ImportaId", c => c.Int());
            AddColumn("dbo.LabKitExameItem", "ImportaId", c => c.Int());
            AddColumn("dbo.LabKitExame", "ImportaId", c => c.Int());
            AddColumn("dbo.LabKit", "ImportaId", c => c.Int());
            AddColumn("dbo.LauModeloLaudo", "ImportaId", c => c.Int());
            AddColumn("dbo.LauMovimento", "ImportaId", c => c.Int());
            AddColumn("dbo.LauMovimentoItem", "ImportaId", c => c.Int());
            AddColumn("dbo.AssSolicitacaoExameItem", "ImportaId", c => c.Int());
            AddColumn("dbo.AssSolicitacaoExame", "ImportaId", c => c.Int());
            AddColumn("dbo.AssPrescricaoMedica", "ImportaId", c => c.Int());
            AddColumn("dbo.AssPrescricaoStatus", "ImportaId", c => c.Int());
            AddColumn("dbo.SisPrestador", "ImportaId", c => c.Int());
            AddColumn("dbo.SisTipoPrestador", "ImportaId", c => c.Int());
            AddColumn("dbo.AssStatusSolicitacaoExameItem", "ImportaId", c => c.Int());
            AddColumn("dbo.LauMovimentoStatus", "ImportaId", c => c.Int());
            AddColumn("dbo.LeitoCaracteristica", "ImportaId", c => c.Int());
            AddColumn("dbo.LeitoServico", "ImportaId", c => c.Int());
            AddColumn("dbo.AteLocalChamada", "ImportaId", c => c.Int());
            AddColumn("dbo.AteLocalChamadaFila", "ImportaId", c => c.Int());
            AddColumn("dbo.MailingTemplate", "ImportaId", c => c.Int());
            AddColumn("dbo.MotivoCancelamento", "ImportaId", c => c.Int());
            AddColumn("dbo.MotivoCaucao", "ImportaId", c => c.Int());
            AddColumn("dbo.MotivoTransferenciaLeito", "ImportaId", c => c.Int());
            AddColumn("dbo.NotaFiscal", "ImportaId", c => c.Int());
            AddColumn("dbo.Orcamento", "ImportaId", c => c.Int());
            AddColumn("dbo.PacienteConvenioBloqueado", "ImportaId", c => c.Int());
            AddColumn("dbo.AtePainel", "ImportaId", c => c.Int());
            AddColumn("dbo.AtePainelTipoLocalChamada", "ImportaId", c => c.Int());
            AddColumn("dbo.Parentesco", "ImportaId", c => c.Int());
            AddColumn("dbo.AssPrescricaoItemHora", "ImportaId", c => c.Int());
            AddColumn("dbo.AssPrescricaoItemResposta", "ImportaId", c => c.Int());
            AddColumn("dbo.AssPrescricaoItemStatus", "ImportaId", c => c.Int());
            AddColumn("dbo.PrestadorCredenciamento", "ImportaId", c => c.Int());
            AddColumn("dbo.PrestadorGrupoProcedimento", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoAcaoTerapeutica", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoCodigoMedicamento", "ImportaId", c => c.Int());
            AddColumn("dbo.Est_ProdutoEmpresa", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoGrupoTratamento", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoLocalizacao", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoPalavraChave", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoPortaria", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoRelacaoAcaoTerapeutica", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoRelacaoLaboratorio", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoRelacaoPalavraChave", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoRelacaoPortaria", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoRelacaoUnidade", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoTipoUnidade", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoSaldoEmprestimo", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoSaldo", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoClasse", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoGrupo", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoSubClasse", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoListaSubstituicao", "ImportaId", c => c.Int());
            AddColumn("dbo.ProdutoSubstancia", "ImportaId", c => c.Int());
            AddColumn("dbo.AssProntuario", "ImportaId", c => c.Int());
            AddColumn("dbo.SisProfissionalSaude", "ImportaId", c => c.Int());
            AddColumn("dbo.AssProntuarioLog", "ImportaId", c => c.Int());
            AddColumn("dbo.Regiao", "ImportaId", c => c.Int());
            AddColumn("dbo.SisRegistroArquivo", "ImportaId", c => c.Int());
            AddColumn("dbo.SisRegistroTabela", "ImportaId", c => c.Int());
            AddColumn("dbo.RelacaoGuiaCampo", "ImportaId", c => c.Int());
            AddColumn("dbo.LabResultado", "ImportaId", c => c.Int());
            AddColumn("dbo.LabTecnico", "ImportaId", c => c.Int());
            AddColumn("dbo.LabResultadoExame", "ImportaId", c => c.Int());
            AddColumn("dbo.LabExameStatus", "ImportaId", c => c.Int());
            AddColumn("dbo.LabResultadoLaudo", "ImportaId", c => c.Int());
            AddColumn("dbo.LabTabelaResultado", "ImportaId", c => c.Int());
            AddColumn("dbo.AteSenha", "ImportaId", c => c.Int());
            AddColumn("dbo.AteSenhaMov", "ImportaId", c => c.Int());
            AddColumn("dbo.AteSenhaMovPainel", "ImportaId", c => c.Int());
            AddColumn("dbo.Sis_Ambulatorio", "ImportaId", c => c.Int());
            AddColumn("dbo.Sis_Atendimento", "ImportaId", c => c.Int());
            AddColumn("dbo.Sis_ContaMedica", "ImportaId", c => c.Int());
            AddColumn("dbo.Sis_Internacao", "ImportaId", c => c.Int());
            AddColumn("dbo.Sis_Paciente", "ImportaId", c => c.Int());
            AddColumn("dbo.Sis_Pessoa", "ImportaId", c => c.Int());
            AddColumn("dbo.SisErro", "ImportaId", c => c.Int());
            AddColumn("dbo.SisMoedaCotacaoItem", "ImportaId", c => c.Int());
            AddColumn("dbo.SisMoedaCotacao", "ImportaId", c => c.Int());
            AddColumn("dbo.SisMoedaCotacaoPlano", "ImportaId", c => c.Int());
            AddColumn("dbo.AssSolicitacaoExamePrioridade", "ImportaId", c => c.Int());
            AddColumn("dbo.SisTarefaIntervalo", "ImportaId", c => c.Int());
            AddColumn("dbo.TenantLogo", "ImportaId", c => c.Int());
            AddColumn("dbo.TipoEntrada", "ImportaId", c => c.Int());
            AddColumn("dbo.TipoUnidade", "ImportaId", c => c.Int());
            AddColumn("dbo.SisUltimoId", "ImportaId", c => c.Int());
            AddColumn("dbo.UnidadeInternacao", "ImportaId", c => c.Int());
            AddColumn("dbo.SisVisualAsaImportExportLog", "ImportaId", c => c.Int());
        }

        public override void Down()
        {
            DropColumn("dbo.SisVisualAsaImportExportLog", "ImportaId");
            DropColumn("dbo.UnidadeInternacao", "ImportaId");
            DropColumn("dbo.SisUltimoId", "ImportaId");
            DropColumn("dbo.TipoUnidade", "ImportaId");
            DropColumn("dbo.TipoEntrada", "ImportaId");
            DropColumn("dbo.TenantLogo", "ImportaId");
            DropColumn("dbo.SisTarefaIntervalo", "ImportaId");
            DropColumn("dbo.AssSolicitacaoExamePrioridade", "ImportaId");
            DropColumn("dbo.SisMoedaCotacaoPlano", "ImportaId");
            DropColumn("dbo.SisMoedaCotacao", "ImportaId");
            DropColumn("dbo.SisMoedaCotacaoItem", "ImportaId");
            DropColumn("dbo.SisErro", "ImportaId");
            DropColumn("dbo.Sis_Pessoa", "ImportaId");
            DropColumn("dbo.Sis_Paciente", "ImportaId");
            DropColumn("dbo.Sis_Internacao", "ImportaId");
            DropColumn("dbo.Sis_ContaMedica", "ImportaId");
            DropColumn("dbo.Sis_Atendimento", "ImportaId");
            DropColumn("dbo.Sis_Ambulatorio", "ImportaId");
            DropColumn("dbo.AteSenhaMovPainel", "ImportaId");
            DropColumn("dbo.AteSenhaMov", "ImportaId");
            DropColumn("dbo.AteSenha", "ImportaId");
            DropColumn("dbo.LabTabelaResultado", "ImportaId");
            DropColumn("dbo.LabResultadoLaudo", "ImportaId");
            DropColumn("dbo.LabExameStatus", "ImportaId");
            DropColumn("dbo.LabResultadoExame", "ImportaId");
            DropColumn("dbo.LabTecnico", "ImportaId");
            DropColumn("dbo.LabResultado", "ImportaId");
            DropColumn("dbo.RelacaoGuiaCampo", "ImportaId");
            DropColumn("dbo.SisRegistroTabela", "ImportaId");
            DropColumn("dbo.SisRegistroArquivo", "ImportaId");
            DropColumn("dbo.Regiao", "ImportaId");
            DropColumn("dbo.AssProntuarioLog", "ImportaId");
            DropColumn("dbo.SisProfissionalSaude", "ImportaId");
            DropColumn("dbo.AssProntuario", "ImportaId");
            DropColumn("dbo.ProdutoSubstancia", "ImportaId");
            DropColumn("dbo.ProdutoListaSubstituicao", "ImportaId");
            DropColumn("dbo.ProdutoSubClasse", "ImportaId");
            DropColumn("dbo.ProdutoGrupo", "ImportaId");
            DropColumn("dbo.ProdutoClasse", "ImportaId");
            DropColumn("dbo.ProdutoSaldo", "ImportaId");
            DropColumn("dbo.ProdutoSaldoEmprestimo", "ImportaId");
            DropColumn("dbo.ProdutoTipoUnidade", "ImportaId");
            DropColumn("dbo.ProdutoRelacaoUnidade", "ImportaId");
            DropColumn("dbo.ProdutoRelacaoPortaria", "ImportaId");
            DropColumn("dbo.ProdutoRelacaoPalavraChave", "ImportaId");
            DropColumn("dbo.ProdutoRelacaoLaboratorio", "ImportaId");
            DropColumn("dbo.ProdutoRelacaoAcaoTerapeutica", "ImportaId");
            DropColumn("dbo.ProdutoPortaria", "ImportaId");
            DropColumn("dbo.ProdutoPalavraChave", "ImportaId");
            DropColumn("dbo.ProdutoLocalizacao", "ImportaId");
            DropColumn("dbo.ProdutoGrupoTratamento", "ImportaId");
            DropColumn("dbo.Est_ProdutoEmpresa", "ImportaId");
            DropColumn("dbo.ProdutoCodigoMedicamento", "ImportaId");
            DropColumn("dbo.ProdutoAcaoTerapeutica", "ImportaId");
            DropColumn("dbo.PrestadorGrupoProcedimento", "ImportaId");
            DropColumn("dbo.PrestadorCredenciamento", "ImportaId");
            DropColumn("dbo.AssPrescricaoItemStatus", "ImportaId");
            DropColumn("dbo.AssPrescricaoItemResposta", "ImportaId");
            DropColumn("dbo.AssPrescricaoItemHora", "ImportaId");
            DropColumn("dbo.Parentesco", "ImportaId");
            DropColumn("dbo.AtePainelTipoLocalChamada", "ImportaId");
            DropColumn("dbo.AtePainel", "ImportaId");
            DropColumn("dbo.PacienteConvenioBloqueado", "ImportaId");
            DropColumn("dbo.Orcamento", "ImportaId");
            DropColumn("dbo.NotaFiscal", "ImportaId");
            DropColumn("dbo.MotivoTransferenciaLeito", "ImportaId");
            DropColumn("dbo.MotivoCaucao", "ImportaId");
            DropColumn("dbo.MotivoCancelamento", "ImportaId");
            DropColumn("dbo.MailingTemplate", "ImportaId");
            DropColumn("dbo.AteLocalChamadaFila", "ImportaId");
            DropColumn("dbo.AteLocalChamada", "ImportaId");
            DropColumn("dbo.LeitoServico", "ImportaId");
            DropColumn("dbo.LeitoCaracteristica", "ImportaId");
            DropColumn("dbo.LauMovimentoStatus", "ImportaId");
            DropColumn("dbo.AssStatusSolicitacaoExameItem", "ImportaId");
            DropColumn("dbo.SisTipoPrestador", "ImportaId");
            DropColumn("dbo.SisPrestador", "ImportaId");
            DropColumn("dbo.AssPrescricaoStatus", "ImportaId");
            DropColumn("dbo.AssPrescricaoMedica", "ImportaId");
            DropColumn("dbo.AssSolicitacaoExame", "ImportaId");
            DropColumn("dbo.AssSolicitacaoExameItem", "ImportaId");
            DropColumn("dbo.LauMovimentoItem", "ImportaId");
            DropColumn("dbo.LauMovimento", "ImportaId");
            DropColumn("dbo.LauModeloLaudo", "ImportaId");
            DropColumn("dbo.LabKit", "ImportaId");
            DropColumn("dbo.LabKitExame", "ImportaId");
            DropColumn("dbo.LabKitExameItem", "ImportaId");
            DropColumn("dbo.InstituicaoTransferencia", "ImportaId");
            DropColumn("dbo.Indicacao", "ImportaId");
            DropColumn("dbo.SisHoraDia", "ImportaId");
            DropColumn("dbo.SisGuiaTipo", "ImportaId");
            DropColumn("dbo.GuiaCampo", "ImportaId");
            DropColumn("dbo.GrupoProcedimento", "ImportaId");
            DropColumn("dbo.GrauInstrucao", "ImportaId");
            DropColumn("dbo.AssFormulaFaturamento", "ImportaId");
            DropColumn("dbo.AssVelocidadeInfusao", "ImportaId");
            DropColumn("dbo.AssTipoControle", "ImportaId");
            DropColumn("dbo.AssFrequencia", "ImportaId");
            DropColumn("dbo.AssPrescricaoItem", "ImportaId");
            DropColumn("dbo.AssFormulaEstoque", "ImportaId");
            DropColumn("dbo.SisFormConfigUnidadeOrganizacional", "ImportaId");
            DropColumn("dbo.SisFormConfigOperacao", "ImportaId");
            DropColumn("dbo.SisFormConfigEspecialidade", "ImportaId");
            DropColumn("dbo.LabTipoResultado", "ImportaId");
            DropColumn("dbo.LabTabela", "ImportaId");
            DropColumn("dbo.LabItemResultado", "ImportaId");
            DropColumn("dbo.LabFormataItem", "ImportaId");
            DropColumn("dbo.FinFormaPagamento", "ImportaId");
            DropColumn("dbo.AssFormaAplicacao", "ImportaId");
            DropColumn("dbo.AteTipoLocalChamada", "ImportaId");
            DropColumn("dbo.AteFila", "ImportaId");
            DropColumn("dbo.Feriado", "ImportaId");
            DropColumn("dbo.SisFavorito", "ImportaId");
            DropColumn("dbo.FatTaxaTurno", "ImportaId");
            DropColumn("dbo.FatTaxaTipoLeito", "ImportaId");
            DropColumn("dbo.FatTaxaLocal", "ImportaId");
            DropColumn("dbo.FatTaxaGrupo", "ImportaId");
            DropColumn("dbo.FatTaxa", "ImportaId");
            DropColumn("dbo.FatTaxaEmpresa", "ImportaId");
            DropColumn("dbo.FatKitItem", "ImportaId");
            DropColumn("dbo.FatItemTabela", "ImportaId");
            DropColumn("dbo.FatItemConfig", "ImportaId");
            DropColumn("dbo.FatFaturamentoItemAutorizacao", "ImportaId");
            DropColumn("dbo.FatItemRelacionamento", "ImportaId");
            DropColumn("dbo.FatItemConfigGlobal", "ImportaId");
            DropColumn("dbo.FatGuiaConvenio", "ImportaId");
            DropColumn("dbo.FatGrupoConvenio", "ImportaId");
            DropColumn("dbo.FatEntregaLote", "ImportaId");
            DropColumn("dbo.FatEntregaConta", "ImportaId");
            DropColumn("dbo.FatTabelaRelacionamento", "ImportaId");
            DropColumn("dbo.FatConvenioRelacionamento", "ImportaId");
            DropColumn("dbo.SisMoeda", "ImportaId");
            DropColumn("dbo.FatTabelaPrecoItem", "ImportaId");
            DropColumn("dbo.SisTurno", "ImportaId");
            DropColumn("dbo.Terceirizado", "ImportaId");
            DropColumn("dbo.FatContaKit", "ImportaId");
            DropColumn("dbo.FatContaItem", "ImportaId");
            DropColumn("dbo.TipoLeito", "ImportaId");
            DropColumn("dbo.FatContaStatus", "ImportaId");
            DropColumn("dbo.FatConta", "ImportaId");
            DropColumn("dbo.FatTabela", "ImportaId");
            DropColumn("dbo.FatConfigConvenio", "ImportaId");
            DropColumn("dbo.FatGlobal", "ImportaId");
            DropColumn("dbo.FatConfigConvenioGlobal", "ImportaId");
            DropColumn("dbo.FatBrasPreco", "ImportaId");
            DropColumn("dbo.FatBrasIndice", "ImportaId");
            DropColumn("dbo.FatBrasImport", "ImportaId");
            DropColumn("dbo.FatBrasApresentacao", "ImportaId");
            DropColumn("dbo.FatAutorizacao", "ImportaId");
            DropColumn("dbo.FatAutorizacaoDetalhe", "ImportaId");
            DropColumn("dbo.QuaEventoMov", "ImportaId");
            DropColumn("dbo.QuaEventoGrupo", "ImportaId");
            DropColumn("dbo.QuaEvento", "ImportaId");
            DropColumn("dbo.EstoqueTransferenciaProdutoItem", "ImportaId");
            DropColumn("dbo.EstoqueTransferenciaProduto", "ImportaId");
            DropColumn("dbo.Est_EstoqueGrupo", "ImportaId");
            DropColumn("dbo.Est_EstoqueEmpresa", "ImportaId");
            DropColumn("dbo.EstoquePreMovimentoLoteValidade", "ImportaId");
            DropColumn("dbo.LoteValidade", "ImportaId");
            DropColumn("dbo.EstoqueMovimentoLoteValidade", "ImportaId");
            DropColumn("dbo.FatBrasLaboratorio", "ImportaId");
            DropColumn("dbo.EstLaboratorio", "ImportaId");
            DropColumn("dbo.EstSolicitacaoItem", "ImportaId");
            DropColumn("dbo.EstItemSolicitacaoAtendida", "ImportaId");
            DropColumn("dbo.EstImportacaoProduto", "ImportaId");
            DropColumn("dbo.EstBaixaEmprestimo", "ImportaId");
            DropColumn("dbo.EstBaixaEmprestimoItem", "ImportaId");
            DropColumn("dbo.EstoquePreMovimentoItem", "ImportaId");
            DropColumn("dbo.EstoqueMovimentoItem", "ImportaId");
            DropColumn("dbo.EstMovimentoBaixaItem", "ImportaId");
            DropColumn("dbo.TipoFrete", "ImportaId");
            DropColumn("dbo.EstoquePreMovimentoEstado", "ImportaId");
            DropColumn("dbo.OrdemCompra", "ImportaId");
            DropColumn("dbo.MotivoPerdaProduto", "ImportaId");
            DropColumn("dbo.EstTipoOperacao", "ImportaId");
            DropColumn("dbo.EstTipoMovimento", "ImportaId");
            DropColumn("dbo.EstoquePreMovimento", "ImportaId");
            DropColumn("dbo.EstGrupoOperacao", "ImportaId");
            DropColumn("dbo.EstoqueMovimento", "ImportaId");
            DropColumn("dbo.EstMovimentoBaixa", "ImportaId");
            DropColumn("dbo.Est_ProdutoEstoque", "ImportaId");
            DropColumn("dbo.EntradaItem", "ImportaId");
            DropColumn("dbo.Entrada", "ImportaId");
            DropColumn("dbo.FinTipoDocumento", "ImportaId");
            DropColumn("dbo.FinDocumentoRateio", "ImportaId");
            DropColumn("dbo.FinSituacaoLancamento", "ImportaId");
            DropColumn("dbo.FinTipoMeioPagamento", "ImportaId");
            DropColumn("dbo.FinMeioPagamento", "ImportaId");
            DropColumn("dbo.FinQuitacao", "ImportaId");
            DropColumn("dbo.FinLancamentoQuitacao", "ImportaId");
            DropColumn("dbo.FinLancamento", "ImportaId");
            DropColumn("dbo.FinDocumento", "ImportaId");
            DropColumn("dbo.DocItem", "ImportaId");
            DropColumn("dbo.SisElementoHtmlTipo", "ImportaId");
            DropColumn("dbo.SisElementoHtml", "ImportaId");
            DropColumn("dbo.AssTipoRespostaConfigElementoHtml", "ImportaId");
            DropColumn("dbo.AssTipoRespostaConfig", "ImportaId");
            DropColumn("dbo.AssTipoRespostaAssTipoRespostaConfig", "ImportaId");
            DropColumn("dbo.AssTipoResposta", "ImportaId");
            DropColumn("dbo.AssTipoPrescricao", "ImportaId");
            DropColumn("dbo.AssDivisao", "ImportaId");
            DropColumn("dbo.AssDivisaoTipoResposta", "ImportaId");
            DropColumn("dbo.ControleProducao", "ImportaId");
            DropColumn("dbo.ConsultorTipoDadoNF", "ImportaId");
            DropColumn("dbo.ConsultorTabelaCampo", "ImportaId");
            DropColumn("dbo.ConsultorTabela", "ImportaId");
            DropColumn("dbo.ConsultorOcorrencia", "ImportaId");
            DropColumn("dbo.CmpRequisicaoTipo", "ImportaId");
            DropColumn("dbo.CmpRequisicaoModo", "ImportaId");
            DropColumn("dbo.CmpMotivoPedido", "ImportaId");
            DropColumn("dbo.CmpCotacaoStatus", "ImportaId");
            DropColumn("dbo.CmpRequisicao", "ImportaId");
            DropColumn("dbo.Est_Unidade", "ImportaId");
            DropColumn("dbo.Est_UnidadeTipo", "ImportaId");
            DropColumn("dbo.Est_ProdutoUnidade", "ImportaId");
            DropColumn("dbo.Est_Genero", "ImportaId");
            DropColumn("dbo.Est_EstoqueLocalizacao", "ImportaId");
            DropColumn("dbo.Est_DCB", "ImportaId");
            DropColumn("dbo.FinGrupoDRE", "ImportaId");
            DropColumn("dbo.FinGrupoContaAdministrativa", "ImportaId");
            DropColumn("dbo.FinSubGrupoContaAdministrativa", "ImportaId");
            DropColumn("dbo.FinRateioCentroCustoItem", "ImportaId");
            DropColumn("dbo.FinRateioCentroCusto", "ImportaId");
            DropColumn("dbo.FinContaAdministrativaEmpresa", "ImportaId");
            DropColumn("dbo.FinContaAdministrativaCentroCusto", "ImportaId");
            DropColumn("dbo.FinContaAdministrativa", "ImportaId");
            DropColumn("dbo.Est_GrupoSubClasse", "ImportaId");
            DropColumn("dbo.Est_Grupo", "ImportaId");
            DropColumn("dbo.Est_GrupoClasse", "ImportaId");
            DropColumn("dbo.Est_Produto", "ImportaId");
            DropColumn("dbo.CmpRequisicaoItem", "ImportaId");
            DropColumn("dbo.TipoPessoa", "ImportaId");
            DropColumn("dbo.SisTipoCadastroExistente", "ImportaId");
            DropColumn("dbo.FornecedorPessoaJuridica", "ImportaId");
            DropColumn("dbo.FornecedorPessoaFisica", "ImportaId");
            DropColumn("dbo.Fornecedor", "ImportaId");
            DropColumn("dbo.CmpCotacaoItem", "ImportaId");
            DropColumn("dbo.CmpAprovacaoStatus", "ImportaId");
            DropColumn("dbo.AteComentarioAutorizacaoProcedimento", "ImportaId");
            DropColumn("dbo.SisProjeto", "ImportaId");
            DropColumn("dbo.DocRotulo", "ImportaId");
            DropColumn("dbo.SisTarefa", "ImportaId");
            DropColumn("dbo.SisComentario", "ImportaId");
            DropColumn("dbo.SisFormRowConfig", "ImportaId");
            DropColumn("dbo.SisFormConfig", "ImportaId");
            DropColumn("dbo.SisFormResposta", "ImportaId");
            DropColumn("dbo.SisFormData", "ImportaId");
            DropColumn("dbo.SisFormColMultiOption", "ImportaId");
            DropColumn("dbo.SisFormColConfig", "ImportaId");
            DropColumn("dbo.PreAtendimento", "ImportaId");
            DropColumn("dbo.ClassificacaoRisco", "ImportaId");
            DropColumn("dbo.FinTipoContaCorrente", "ImportaId");
            DropColumn("dbo.FinContaCorrente", "ImportaId");
            DropColumn("dbo.FinTalaoCheque", "ImportaId");
            DropColumn("dbo.FinCheque", "ImportaId");
            DropColumn("dbo.Cfop", "ImportaId");
            DropColumn("dbo.CapituloCID", "ImportaId");
            DropColumn("dbo.SisOperacao", "ImportaId");
            DropColumn("dbo.SisModulo", "ImportaId");
            DropColumn("dbo.SisBI", "ImportaId");
            DropColumn("dbo.SisBairro", "ImportaId");
            DropColumn("dbo.AteStatusSolicitacaoProcedimento", "ImportaId");
            DropColumn("dbo.FatSubGrupo", "ImportaId");
            DropColumn("dbo.LauModalidade", "ImportaId");
            DropColumn("dbo.LauGrupo", "ImportaId");
            DropColumn("dbo.FatKit", "ImportaId");
            DropColumn("dbo.FatTipoGrupo", "ImportaId");
            DropColumn("dbo.FatGrupo", "ImportaId");
            DropColumn("dbo.LabUnidade", "ImportaId");
            DropColumn("dbo.LabSetor", "ImportaId");
            DropColumn("dbo.LabMetodo", "ImportaId");
            DropColumn("dbo.LabMaterial", "ImportaId");
            DropColumn("dbo.LabMapa", "ImportaId");
            DropColumn("dbo.LabFormata", "ImportaId");
            DropColumn("dbo.LabExame", "ImportaId");
            DropColumn("dbo.LabEquipamento", "ImportaId");
            DropColumn("dbo.FatBrasItem", "ImportaId");
            DropColumn("dbo.FatItem", "ImportaId");
            DropColumn("dbo.AteAutorizacaoProcedimentoItem", "ImportaId");
            DropColumn("dbo.AteAutorizacaoProcedimento", "ImportaId");
            DropColumn("dbo.SisFornecedor", "ImportaId");
            DropColumn("dbo.AteVisitante", "ImportaId");
            DropColumn("dbo.AssTipoAtestado", "ImportaId");
            DropColumn("dbo.AssModeloAtestado", "ImportaId");
            DropColumn("dbo.AssAtestado", "ImportaId");
            DropColumn("dbo.UserEmpresas", "ImportaId");
            DropColumn("dbo.ServicoMedicoPrestado", "ImportaId");
            DropColumn("dbo.SisOrigem", "ImportaId");
            DropColumn("dbo.AssMotivoAltaTipoAlta", "ImportaId");
            DropColumn("dbo.AssMotivoAlta", "ImportaId");
            DropColumn("dbo.SisTipoAcomodacao", "ImportaId");
            DropColumn("dbo.SisVersaoTiss", "ImportaId");
            DropColumn("dbo.SisTipoTabelaDominio", "ImportaId");
            DropColumn("dbo.SisGrupoTipoTabelaDominio", "ImportaId");
            DropColumn("dbo.SisTabelaDominio", "ImportaId");
            DropColumn("dbo.LeitoStatus", "ImportaId");
            DropColumn("dbo.AteLeito", "ImportaId");
            DropColumn("dbo.SisGuia", "ImportaId");
            DropColumn("dbo.FatGuia", "ImportaId");
            DropColumn("dbo.AteUnidadeInternacaoTipo", "ImportaId");
            DropColumn("dbo.GrupoCentroCusto", "ImportaId");
            DropColumn("dbo.CentroCusto", "ImportaId");
            DropColumn("dbo.SisUnidadeOrganizacional", "ImportaId");
            DropColumn("dbo.Est_Estoque", "ImportaId");
            DropColumn("dbo.SisEmpresa", "ImportaId");
            DropColumn("dbo.AteTipoAtendimento", "ImportaId");
            DropColumn("dbo.GrupoCID", "ImportaId");
            DropColumn("dbo.AteAtendimento", "ImportaId");
            DropColumn("dbo.AteAtendimentoLeitoMov", "ImportaId");
            DropColumn("dbo.SisPlano", "ImportaId");
            DropColumn("dbo.PacientePeso", "ImportaId");
            DropColumn("dbo.SisPaciente", "ImportaId");
            DropColumn("dbo.SisCep", "ImportaId");
            DropColumn("dbo.SisConvenio", "ImportaId");
            DropColumn("dbo.AgendamentoConsulta", "ImportaId");
            DropColumn("dbo.TipoVinculoEmpregaticio", "ImportaId");
            DropColumn("dbo.SisTipoParticipacao", "ImportaId");
            DropColumn("dbo.SisTipoTelefone", "ImportaId");
            DropColumn("dbo.SisTipoSanguineo", "ImportaId");
            DropColumn("dbo.SisTipoPessoa", "ImportaId");
            DropColumn("dbo.SisTipoLogradouro", "ImportaId");
            DropColumn("dbo.TipoEnderecoes", "ImportaId");
            DropColumn("dbo.SisEndereco", "ImportaId");
            DropColumn("dbo.SisPessoa", "ImportaId");
            DropColumn("dbo.SisSexo", "ImportaId");
            DropColumn("dbo.SisReligiao", "ImportaId");
            DropColumn("dbo.SisProfissao", "ImportaId");
            DropColumn("dbo.SisNaturalidade", "ImportaId");
            DropColumn("dbo.SisNacionalidade", "ImportaId");
            DropColumn("dbo.SisCboTipo", "ImportaId");
            DropColumn("dbo.SisCboFamilia", "ImportaId");
            DropColumn("dbo.SisCbo", "ImportaId");
            DropColumn("dbo.SisEspecialidade", "ImportaId");
            DropColumn("dbo.SisMedicoEspecialidade", "ImportaId");
            DropColumn("dbo.SisEstadoCivil", "ImportaId");
            DropColumn("dbo.SisEscolaridade", "ImportaId");
            DropColumn("dbo.CorPele", "ImportaId");
            DropColumn("dbo.SisConselho", "ImportaId");
            DropColumn("dbo.SisPais", "ImportaId");
            DropColumn("dbo.SisEstado", "ImportaId");
            DropColumn("dbo.SisCidade", "ImportaId");
            DropColumn("dbo.SisMedico", "ImportaId");
            DropColumn("dbo.AteIntervalo", "ImportaId");
            DropColumn("dbo.AteAgendamentoConsultaMedicoDisponibilidade", "ImportaId");
            DropColumn("dbo.FinBanco", "ImportaId");
            DropColumn("dbo.FinAgencia", "ImportaId");
        }
    }
}
