// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Inserindo_Relacionamento_Atendimento_em_AutorizacaoProcedimento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inserindo_Relacionamento_Atendimento_em_AutorizacaoProcedimento));
        
        string IMigrationMetadata.Id
        {
            get { return "201811141840338_Inserindo_Relacionamento_Atendimento_em_AutorizacaoProcedimento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
