namespace SW10.SWMANAGER.Migrations
{
    using System.Data.Entity.Migrations;

    public partial class Ajuste_Paciente_Medico : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.SisPessoa", "TipoPessoaId", "dbo.SisTipoPessoa");
            DropIndex("dbo.SisPessoa", new[] { "TipoPessoaId" });
            AddColumn("dbo.SisPessoa", "TipoLogradouroId", c => c.Long());
            AddColumn("dbo.SisPessoa", "TipoSanguineoId", c => c.Long());
            AddColumn("dbo.SisPessoa", "CorPeleId", c => c.Long());
            AddColumn("dbo.SisPessoa", "EstadoCivilId", c => c.Long());
            AddColumn("dbo.SisPessoa", "EscolaridadeId", c => c.Long());
            AddColumn("dbo.SisPessoa", "TipoTelefone1Id", c => c.Long());
            AddColumn("dbo.SisPessoa", "TipoTelefone2Id", c => c.Long());
            AddColumn("dbo.SisPessoa", "TipoTelefone3Id", c => c.Long());
            AddColumn("dbo.SisPessoa", "TipoTelefone4Id", c => c.Long());
            AddColumn("dbo.SisMedico", "CorPeleId", c => c.Long());
            AddColumn("dbo.SisMedico", "EscolaridadeId", c => c.Long());
            AddColumn("dbo.SisMedico", "EstadoCivilId", c => c.Long());
            AddColumn("dbo.SisMedico", "TipoTelefone1Id", c => c.Long());
            AddColumn("dbo.SisMedico", "TipoTelefone2Id", c => c.Long());
            AddColumn("dbo.SisMedico", "TipoTelefone3Id", c => c.Long());
            AddColumn("dbo.SisMedico", "TipoTelefone4Id", c => c.Long());
            AddColumn("dbo.SisPaciente", "CorPeleId", c => c.Long());
            AddColumn("dbo.SisPaciente", "EscolaridadeId", c => c.Long());
            AddColumn("dbo.SisPaciente", "EstadoCivilId", c => c.Long());
            AddColumn("dbo.SisPaciente", "TipoTelefone1Id", c => c.Long());
            AddColumn("dbo.SisPaciente", "TipoTelefone2Id", c => c.Long());
            AddColumn("dbo.SisPaciente", "TipoTelefone3Id", c => c.Long());
            AddColumn("dbo.SisPaciente", "TipoTelefone4Id", c => c.Long());
            AlterColumn("dbo.SisPessoa", "TipoPessoaId", c => c.Long());
            CreateIndex("dbo.SisPessoa", "TipoLogradouroId");
            CreateIndex("dbo.SisPessoa", "TipoSanguineoId");
            CreateIndex("dbo.SisPessoa", "CorPeleId");
            CreateIndex("dbo.SisPessoa", "EstadoCivilId");
            CreateIndex("dbo.SisPessoa", "EscolaridadeId");
            CreateIndex("dbo.SisPessoa", "TipoPessoaId");
            CreateIndex("dbo.SisPessoa", "TipoTelefone1Id");
            CreateIndex("dbo.SisPessoa", "TipoTelefone2Id");
            CreateIndex("dbo.SisPessoa", "TipoTelefone3Id");
            CreateIndex("dbo.SisPessoa", "TipoTelefone4Id");
            CreateIndex("dbo.SisMedico", "CorPeleId");
            CreateIndex("dbo.SisMedico", "EscolaridadeId");
            CreateIndex("dbo.SisMedico", "EstadoCivilId");
            CreateIndex("dbo.SisMedico", "TipoTelefone1Id");
            CreateIndex("dbo.SisMedico", "TipoTelefone2Id");
            CreateIndex("dbo.SisMedico", "TipoTelefone3Id");
            CreateIndex("dbo.SisMedico", "TipoTelefone4Id");
            CreateIndex("dbo.SisPaciente", "CorPeleId");
            CreateIndex("dbo.SisPaciente", "EscolaridadeId");
            CreateIndex("dbo.SisPaciente", "EstadoCivilId");
            CreateIndex("dbo.SisPaciente", "TipoTelefone1Id");
            CreateIndex("dbo.SisPaciente", "TipoTelefone2Id");
            CreateIndex("dbo.SisPaciente", "TipoTelefone3Id");
            CreateIndex("dbo.SisPaciente", "TipoTelefone4Id");
            AddForeignKey("dbo.SisPessoa", "CorPeleId", "dbo.CorPele", "Id");
            AddForeignKey("dbo.SisPessoa", "EscolaridadeId", "dbo.SisEscolaridade", "Id");
            AddForeignKey("dbo.SisPessoa", "EstadoCivilId", "dbo.SisEstadoCivil", "Id");
            AddForeignKey("dbo.SisPessoa", "TipoLogradouroId", "dbo.SisTipoLogradouro", "Id");
            AddForeignKey("dbo.SisPessoa", "TipoSanguineoId", "dbo.SisTipoSanguineo", "Id");
            AddForeignKey("dbo.SisPessoa", "TipoTelefone1Id", "dbo.SisTipoTelefone", "Id");
            AddForeignKey("dbo.SisPessoa", "TipoTelefone2Id", "dbo.SisTipoTelefone", "Id");
            AddForeignKey("dbo.SisPessoa", "TipoTelefone3Id", "dbo.SisTipoTelefone", "Id");
            AddForeignKey("dbo.SisPessoa", "TipoTelefone4Id", "dbo.SisTipoTelefone", "Id");
            AddForeignKey("dbo.SisMedico", "CorPeleId", "dbo.CorPele", "Id");
            AddForeignKey("dbo.SisMedico", "EscolaridadeId", "dbo.SisEscolaridade", "Id");
            AddForeignKey("dbo.SisMedico", "EstadoCivilId", "dbo.SisEstadoCivil", "Id");
            AddForeignKey("dbo.SisMedico", "TipoTelefone1Id", "dbo.SisTipoTelefone", "Id");
            AddForeignKey("dbo.SisMedico", "TipoTelefone2Id", "dbo.SisTipoTelefone", "Id");
            AddForeignKey("dbo.SisMedico", "TipoTelefone3Id", "dbo.SisTipoTelefone", "Id");
            AddForeignKey("dbo.SisMedico", "TipoTelefone4Id", "dbo.SisTipoTelefone", "Id");
            AddForeignKey("dbo.SisPaciente", "CorPeleId", "dbo.CorPele", "Id");
            AddForeignKey("dbo.SisPaciente", "EscolaridadeId", "dbo.SisEscolaridade", "Id");
            AddForeignKey("dbo.SisPaciente", "EstadoCivilId", "dbo.SisEstadoCivil", "Id");
            AddForeignKey("dbo.SisPaciente", "TipoTelefone1Id", "dbo.SisTipoTelefone", "Id");
            AddForeignKey("dbo.SisPaciente", "TipoTelefone2Id", "dbo.SisTipoTelefone", "Id");
            AddForeignKey("dbo.SisPaciente", "TipoTelefone3Id", "dbo.SisTipoTelefone", "Id");
            AddForeignKey("dbo.SisPaciente", "TipoTelefone4Id", "dbo.SisTipoTelefone", "Id");
            AddForeignKey("dbo.SisPessoa", "TipoPessoaId", "dbo.SisTipoPessoa", "Id");
            DropColumn("dbo.SisPessoa", "CorPele");
            DropColumn("dbo.SisPessoa", "Escolaridade");
            DropColumn("dbo.SisPessoa", "EstadoCivil");
            DropColumn("dbo.SisPessoa", "TipoTelefone1");
            DropColumn("dbo.SisPessoa", "TipoTelefone2");
            DropColumn("dbo.SisPessoa", "TipoTelefone3");
            DropColumn("dbo.SisPessoa", "TipoTelefone4");
            DropColumn("dbo.SisMedico", "CorPele");
            DropColumn("dbo.SisMedico", "Escolaridade");
            DropColumn("dbo.SisMedico", "EstadoCivil");
            DropColumn("dbo.SisMedico", "TipoTelefone1");
            DropColumn("dbo.SisMedico", "TipoTelefone2");
            DropColumn("dbo.SisMedico", "TipoTelefone3");
            DropColumn("dbo.SisMedico", "TipoTelefone4");
            DropColumn("dbo.SisPaciente", "CorPele");
            DropColumn("dbo.SisPaciente", "Escolaridade");
            DropColumn("dbo.SisPaciente", "EstadoCivil");
            DropColumn("dbo.SisPaciente", "TipoTelefone1");
            DropColumn("dbo.SisPaciente", "TipoTelefone2");
            DropColumn("dbo.SisPaciente", "TipoTelefone3");
            DropColumn("dbo.SisPaciente", "TipoTelefone4");
        }

        public override void Down()
        {
            AddColumn("dbo.SisPaciente", "TipoTelefone4", c => c.Int());
            AddColumn("dbo.SisPaciente", "TipoTelefone3", c => c.Int());
            AddColumn("dbo.SisPaciente", "TipoTelefone2", c => c.Int());
            AddColumn("dbo.SisPaciente", "TipoTelefone1", c => c.Int());
            AddColumn("dbo.SisPaciente", "EstadoCivil", c => c.Int());
            AddColumn("dbo.SisPaciente", "Escolaridade", c => c.Int());
            AddColumn("dbo.SisPaciente", "CorPele", c => c.Int());
            AddColumn("dbo.SisMedico", "TipoTelefone4", c => c.Int());
            AddColumn("dbo.SisMedico", "TipoTelefone3", c => c.Int());
            AddColumn("dbo.SisMedico", "TipoTelefone2", c => c.Int());
            AddColumn("dbo.SisMedico", "TipoTelefone1", c => c.Int());
            AddColumn("dbo.SisMedico", "EstadoCivil", c => c.Int());
            AddColumn("dbo.SisMedico", "Escolaridade", c => c.Int());
            AddColumn("dbo.SisMedico", "CorPele", c => c.Int());
            AddColumn("dbo.SisPessoa", "TipoTelefone4", c => c.Int());
            AddColumn("dbo.SisPessoa", "TipoTelefone3", c => c.Int());
            AddColumn("dbo.SisPessoa", "TipoTelefone2", c => c.Int());
            AddColumn("dbo.SisPessoa", "TipoTelefone1", c => c.Int());
            AddColumn("dbo.SisPessoa", "EstadoCivil", c => c.Int());
            AddColumn("dbo.SisPessoa", "Escolaridade", c => c.Int());
            AddColumn("dbo.SisPessoa", "CorPele", c => c.Int());
            DropForeignKey("dbo.SisPessoa", "TipoPessoaId", "dbo.SisTipoPessoa");
            DropForeignKey("dbo.SisPaciente", "TipoTelefone4Id", "dbo.SisTipoTelefone");
            DropForeignKey("dbo.SisPaciente", "TipoTelefone3Id", "dbo.SisTipoTelefone");
            DropForeignKey("dbo.SisPaciente", "TipoTelefone2Id", "dbo.SisTipoTelefone");
            DropForeignKey("dbo.SisPaciente", "TipoTelefone1Id", "dbo.SisTipoTelefone");
            DropForeignKey("dbo.SisPaciente", "EstadoCivilId", "dbo.SisEstadoCivil");
            DropForeignKey("dbo.SisPaciente", "EscolaridadeId", "dbo.SisEscolaridade");
            DropForeignKey("dbo.SisPaciente", "CorPeleId", "dbo.CorPele");
            DropForeignKey("dbo.SisMedico", "TipoTelefone4Id", "dbo.SisTipoTelefone");
            DropForeignKey("dbo.SisMedico", "TipoTelefone3Id", "dbo.SisTipoTelefone");
            DropForeignKey("dbo.SisMedico", "TipoTelefone2Id", "dbo.SisTipoTelefone");
            DropForeignKey("dbo.SisMedico", "TipoTelefone1Id", "dbo.SisTipoTelefone");
            DropForeignKey("dbo.SisMedico", "EstadoCivilId", "dbo.SisEstadoCivil");
            DropForeignKey("dbo.SisMedico", "EscolaridadeId", "dbo.SisEscolaridade");
            DropForeignKey("dbo.SisMedico", "CorPeleId", "dbo.CorPele");
            DropForeignKey("dbo.SisPessoa", "TipoTelefone4Id", "dbo.SisTipoTelefone");
            DropForeignKey("dbo.SisPessoa", "TipoTelefone3Id", "dbo.SisTipoTelefone");
            DropForeignKey("dbo.SisPessoa", "TipoTelefone2Id", "dbo.SisTipoTelefone");
            DropForeignKey("dbo.SisPessoa", "TipoTelefone1Id", "dbo.SisTipoTelefone");
            DropForeignKey("dbo.SisPessoa", "TipoSanguineoId", "dbo.SisTipoSanguineo");
            DropForeignKey("dbo.SisPessoa", "TipoLogradouroId", "dbo.SisTipoLogradouro");
            DropForeignKey("dbo.SisPessoa", "EstadoCivilId", "dbo.SisEstadoCivil");
            DropForeignKey("dbo.SisPessoa", "EscolaridadeId", "dbo.SisEscolaridade");
            DropForeignKey("dbo.SisPessoa", "CorPeleId", "dbo.CorPele");
            DropIndex("dbo.SisPaciente", new[] { "TipoTelefone4Id" });
            DropIndex("dbo.SisPaciente", new[] { "TipoTelefone3Id" });
            DropIndex("dbo.SisPaciente", new[] { "TipoTelefone2Id" });
            DropIndex("dbo.SisPaciente", new[] { "TipoTelefone1Id" });
            DropIndex("dbo.SisPaciente", new[] { "EstadoCivilId" });
            DropIndex("dbo.SisPaciente", new[] { "EscolaridadeId" });
            DropIndex("dbo.SisPaciente", new[] { "CorPeleId" });
            DropIndex("dbo.SisMedico", new[] { "TipoTelefone4Id" });
            DropIndex("dbo.SisMedico", new[] { "TipoTelefone3Id" });
            DropIndex("dbo.SisMedico", new[] { "TipoTelefone2Id" });
            DropIndex("dbo.SisMedico", new[] { "TipoTelefone1Id" });
            DropIndex("dbo.SisMedico", new[] { "EstadoCivilId" });
            DropIndex("dbo.SisMedico", new[] { "EscolaridadeId" });
            DropIndex("dbo.SisMedico", new[] { "CorPeleId" });
            DropIndex("dbo.SisPessoa", new[] { "TipoTelefone4Id" });
            DropIndex("dbo.SisPessoa", new[] { "TipoTelefone3Id" });
            DropIndex("dbo.SisPessoa", new[] { "TipoTelefone2Id" });
            DropIndex("dbo.SisPessoa", new[] { "TipoTelefone1Id" });
            DropIndex("dbo.SisPessoa", new[] { "TipoPessoaId" });
            DropIndex("dbo.SisPessoa", new[] { "EscolaridadeId" });
            DropIndex("dbo.SisPessoa", new[] { "EstadoCivilId" });
            DropIndex("dbo.SisPessoa", new[] { "CorPeleId" });
            DropIndex("dbo.SisPessoa", new[] { "TipoSanguineoId" });
            DropIndex("dbo.SisPessoa", new[] { "TipoLogradouroId" });
            AlterColumn("dbo.SisPessoa", "TipoPessoaId", c => c.Long(nullable: false));
            DropColumn("dbo.SisPaciente", "TipoTelefone4Id");
            DropColumn("dbo.SisPaciente", "TipoTelefone3Id");
            DropColumn("dbo.SisPaciente", "TipoTelefone2Id");
            DropColumn("dbo.SisPaciente", "TipoTelefone1Id");
            DropColumn("dbo.SisPaciente", "EstadoCivilId");
            DropColumn("dbo.SisPaciente", "EscolaridadeId");
            DropColumn("dbo.SisPaciente", "CorPeleId");
            DropColumn("dbo.SisMedico", "TipoTelefone4Id");
            DropColumn("dbo.SisMedico", "TipoTelefone3Id");
            DropColumn("dbo.SisMedico", "TipoTelefone2Id");
            DropColumn("dbo.SisMedico", "TipoTelefone1Id");
            DropColumn("dbo.SisMedico", "EstadoCivilId");
            DropColumn("dbo.SisMedico", "EscolaridadeId");
            DropColumn("dbo.SisMedico", "CorPeleId");
            DropColumn("dbo.SisPessoa", "TipoTelefone4Id");
            DropColumn("dbo.SisPessoa", "TipoTelefone3Id");
            DropColumn("dbo.SisPessoa", "TipoTelefone2Id");
            DropColumn("dbo.SisPessoa", "TipoTelefone1Id");
            DropColumn("dbo.SisPessoa", "EscolaridadeId");
            DropColumn("dbo.SisPessoa", "EstadoCivilId");
            DropColumn("dbo.SisPessoa", "CorPeleId");
            DropColumn("dbo.SisPessoa", "TipoSanguineoId");
            DropColumn("dbo.SisPessoa", "TipoLogradouroId");
            CreateIndex("dbo.SisPessoa", "TipoPessoaId");
            AddForeignKey("dbo.SisPessoa", "TipoPessoaId", "dbo.SisTipoPessoa", "Id", cascadeDelete: true);
        }
    }
}
