// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class especialidade_chaves_estrangeiras : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(especialidade_chaves_estrangeiras));
        
        string IMigrationMetadata.Id
        {
            get { return "201801252344521_especialidade_chaves_estrangeiras"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
