// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TipoMovimento_add_columns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TipoMovimento_add_columns));
        
        string IMigrationMetadata.Id
        {
            get { return "201811291809536_TipoMovimento_add_columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
