// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AccessNumber_No_LaudoMovimentoItemDto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccessNumber_No_LaudoMovimentoItemDto));
        
        string IMigrationMetadata.Id
        {
            get { return "201909271502338_AccessNumber_No_LaudoMovimentoItemDto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
