// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ConfiguracaoPrescricaoItem_Alterações : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConfiguracaoPrescricaoItem_Alterações));
        
        string IMigrationMetadata.Id
        {
            get { return "202012281847318_ConfiguracaoPrescricaoItem_Alterações"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
