// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ICMS_NOTA_ENTRADA1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ICMS_NOTA_ENTRADA1));
        
        string IMigrationMetadata.Id
        {
            get { return "202010161408339_ICMS_NOTA_ENTRADA1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
