// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Criando_Atualizando_Tabelas_Compras : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criando_Atualizando_Tabelas_Compras));
        
        string IMigrationMetadata.Id
        {
            get { return "202210171030147_Criando_Atualizando_Tabelas_Compras"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
