// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Criando_Controle_Bancario_Tipo_Documento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criando_Controle_Bancario_Tipo_Documento));
        
        string IMigrationMetadata.Id
        {
            get { return "202210012044483_Criando_Controle_Bancario_Tipo_Documento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
