// <auto-generated />
namespace SW10.SWMANAGER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Faturamento_Alteracoes_Add_Qtde_FatPacote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Faturamento_Alteracoes_Add_Qtde_FatPacote));
        
        string IMigrationMetadata.Id
        {
            get { return "202201181805289_Faturamento_Alteracoes_Add_Qtde_FatPacote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
