namespace SW10.SWMANAGER.ClassesAplicacao.Cadastros.TiposTabelaDominio
{
    public enum EnumTipoTabelaDominio
    {
        DiariasTaxasGasesMedicinais = 1,
        MateriaisOrtesesProtesesMateriaisEspeciais_OPME = 2,
        Medicamento = 3,
        ProcedimentosEventosEmSaude = 4,
        CaraterAtendimento = 5,
        ClassificaçãoBrasileiraOcupações_CBO = 6,
        CodigoDespesa = 7,
        ConselhoProfissional = 8,
        DébitosCredito = 9,
        Dente = 10,
        DiagnosticoPorImagem = 11,
        EscalaCapacidadeFuncional_ECOG_EscalaZubrod = 12,
        EstadiamentoTumor = 13,
        FacesDente = 14,
        FinalidadeTratamento = 15,
        FormaPagamento = 16,
        GrauParticipacao = 17,
        IndicadorAcidente = 18,
        IndicadorDébitoCredito = 19,
        Mensagens_GlosasNegativasOutras = 20,
        MotivoEncerramento = 21,
        OrigemGuia = 22,
        RegimeInternacao = 23,
        RegioesBoca = 24,
        Sexo = 25,
        SituacaoInicialDente = 26,
        StatusSolicitacao = 27,
        StatusCancelamento = 28,
        StatusProtocolo = 29,
        TecnicaUtilizada = 30,
        TipoAcomodacao = 31,
        TipoAtendimento = 32,
        TipoAtendimentoOdontologia = 33,
        TipoConsulta = 34,
        TipoDemonstrativo = 35,
        TipoGuia = 36,
        TipoFaturamento = 37,
        NaturezaGuia = 38,
        TipoInternação = 39,
        TipoQuimioterapia = 40,
        UnidadeFederação = 41,
        UnidadeMedida = 42,
        ViaAcesso = 43,
        ViaAdministracao = 44,
        GruposProcedimentosItensAssistenciaisEnvioPara_ANS = 45,
        FormaEnvioProcedimentosItensAssistenciaisPara_ANS = 46,
        Metastases = 47,
        Nodulo = 48,
        Tumor = 49,
        CategoriaDespesa = 50,
        VersaoPadrao = 51,
        FormaEnvioPadrão = 52,
        TipoAtendimentoPorOperadoraIntermediario = 53,
        RelacaoTerminologiasUnificadasSaudeSuplementar = 54


    }
}
